//! `bash --rcfile` **replaces** the developer's `.bashrc` rather than adding to
//! it, so the generated file sources theirs first.

use crate::tasks::Ctx;
use anyhow::Result;
use std::path::Path;

pub fn rcfile(home: &Path, banner: &str) -> String {
    format!(
        r#"# Generated by riabuild. Edits here are overwritten.
#
# --rcfile replaces ~/.bashrc entirely, so the developer's own configuration is
# sourced first and riabuild only adds on top.

[ -f "{home}/.bashrc" ] && source "{home}/.bashrc"

{banner}
"#,
        home = home.display(),
    )
}

pub fn banner_command(text: &str) -> String {
    format!("printf '%s\\n' {}", shell_quote(text))
}

fn shell_quote(text: &str) -> String {
    format!("'{}'", text.replace('\'', r"'\''"))
}

pub async fn prepare(ctx: &Ctx) -> Result<super::ShellLaunch> {
    let dir = ctx.paths.shell_dir("bash");
    tokio::fs::create_dir_all(&dir).await?;
    let rc = dir.join("rc");
    tokio::fs::write(
        &rc,
        rcfile(&ctx.paths.home(), &banner_command(super::BANNER)),
    )
    .await?;

    Ok((
        vec![
            "--rcfile".to_string(),
            rc.to_string_lossy().into_owned(),
            "-i".to_string(),
        ],
        Vec::new(),
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sources_the_developers_bashrc_first() {
        let generated = rcfile(Path::new("/Users/ada"), "printf hi");
        let source_line = generated.find("/Users/ada/.bashrc").unwrap();
        let banner_line = generated.find("printf hi").unwrap();
        assert!(source_line < banner_line, "{generated}");
    }

    #[test]
    fn survives_a_developer_with_no_bashrc() {
        assert!(rcfile(Path::new("/Users/ada"), "").contains(r#"[ -f "/Users/ada/.bashrc" ]"#));
    }
}
