//! `bash --rcfile` **replaces** the developer's `.bashrc` rather than adding to
//! it, so the generated file sources theirs first.

use crate::tasks::Ctx;
use anyhow::Result;
use std::path::Path;

pub fn rcfile(home: &Path, banner: &str, prompt: &str) -> String {
    format!(
        r#"# Generated by riabuild. Edits here are overwritten.
#
# --rcfile replaces ~/.bashrc entirely, so the developer's own configuration is
# sourced first and riabuild only adds on top.

[ -f "{home}/.bashrc" ] && source "{home}/.bashrc"

{prompt}

{banner}
"#,
        home = home.display(),
    )
}

/// Guarded on stdout being a terminal — see the note in `zsh::banner_command`.
/// `if` rather than `&&` so a non-terminal shell does not start with a
/// non-zero `$?` for the developer's prompt to report as a failure.
pub fn banner_command(text: &str) -> String {
    format!("if [ -t 1 ]; then printf '%s\\n' {}; fi", shell_quote(text))
}

/// Prefixes `PS1` from a `PROMPT_COMMAND` hook rather than assigning it once.
///
/// A one-time prepend is undone by anything that rebuilds `PS1` per render —
/// starship, oh-my-bash, a hand-rolled git-branch prompt. Appending to
/// `PROMPT_COMMAND` puts riabuild after whatever the developer installed.
///
/// Two details that are easy to get wrong:
///
/// * `\[` and `\]` mark the colour escapes as zero-width. Without them bash
///   counts them as visible columns and wraps long command lines over
///   themselves.
/// * `PROMPT_COMMAND` is an array in bash 5.1 and later, and a string
///   everywhere else — including the bash 3.2 that ships with macOS. Assigning
///   a string over an array would overwrite the developer's first hook, so the
///   two cases are handled separately.
pub fn prompt_command(colour: bool) -> String {
    let prefix = if colour {
        format!(r"\[\033[1;34m\]{}\[\033[0m\] ", super::PROMPT_LABEL)
    } else {
        format!("{} ", super::PROMPT_LABEL)
    };
    format!(
        r#"_riabuild_prefix={prefix}
_riabuild_prompt() {{
    case "$PS1" in
        "$_riabuild_prefix"*) ;;
        *) PS1="$_riabuild_prefix$PS1" ;;
    esac
}}
case "$(declare -p PROMPT_COMMAND 2>/dev/null)" in
    declare\ -a*|typeset\ -a*) PROMPT_COMMAND+=(_riabuild_prompt) ;;
    *) PROMPT_COMMAND="${{PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}}_riabuild_prompt" ;;
esac"#,
        prefix = shell_quote(&prefix),
    )
}

fn shell_quote(text: &str) -> String {
    format!("'{}'", text.replace('\'', r"'\''"))
}

pub fn prepare(ctx: &Ctx) -> Result<super::ShellLaunch> {
    let dir = ctx.paths.shell_dir("bash");
    std::fs::create_dir_all(&dir)?;
    let rc = dir.join("rc");
    let colour = ctx.ui.colour();
    std::fs::write(
        &rc,
        rcfile(
            &ctx.paths.home(),
            &banner_command(&super::banner(colour)),
            &prompt_command(colour),
        ),
    )?;

    Ok((
        vec![
            "--rcfile".to_string(),
            rc.to_string_lossy().into_owned(),
            "-i".to_string(),
        ],
        Vec::new(),
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sources_the_developers_bashrc_first() {
        let generated = rcfile(Path::new("/Users/ada"), "printf hi", "# prompt");
        let source_line = generated.find("/Users/ada/.bashrc").unwrap();
        let banner_line = generated.find("printf hi").unwrap();
        assert!(source_line < banner_line, "{generated}");
        assert!(
            source_line < generated.find("# prompt").unwrap(),
            "{generated}"
        );
    }

    #[test]
    fn survives_a_developer_with_no_bashrc() {
        assert!(rcfile(Path::new("/Users/ada"), "", "").contains(r#"[ -f "/Users/ada/.bashrc" ]"#));
    }

    #[test]
    fn the_banner_only_prints_to_a_terminal() {
        let command = banner_command("hi");
        assert!(command.starts_with("if [ -t 1 ]; then "), "{command}");
        assert!(command.ends_with("; fi"), "{command}");
    }

    #[test]
    fn colour_escapes_are_marked_zero_width() {
        // Unmarked escapes make bash mismeasure the prompt, and typing past the
        // terminal width starts overwriting the line.
        let coloured = prompt_command(true);
        assert!(
            coloured.contains(r"\[\033[1;34m\](riabuild)\[\033[0m\]"),
            "{coloured}"
        );
    }

    #[test]
    fn no_colour_means_no_escapes_at_all() {
        let plain = prompt_command(false);
        assert!(plain.contains("_riabuild_prefix='(riabuild) '"), "{plain}");
        assert!(!plain.contains(r"\033"), "{plain}");
    }

    #[test]
    fn the_prefix_is_applied_once_and_appended_after_the_developers_hook() {
        let generated = prompt_command(true);
        assert!(
            generated.contains(r#""$_riabuild_prefix"*) ;;"#),
            "{generated}"
        );
        // Existing PROMPT_COMMAND is preserved and riabuild goes last.
        assert!(
            generated.contains(r#"${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}_riabuild_prompt"#),
            "{generated}"
        );
    }

    #[test]
    fn an_array_prompt_command_is_appended_to_rather_than_replaced() {
        // bash 5.1+ makes PROMPT_COMMAND an array; assigning a string to it
        // would clobber the developer's first hook.
        let generated = prompt_command(true);
        assert!(
            generated.contains("PROMPT_COMMAND+=(_riabuild_prompt)"),
            "{generated}"
        );
    }
}
