//! fish reads `$XDG_CONFIG_HOME/fish/config.fish`, so riabuild points
//! `XDG_CONFIG_HOME` at a directory of its own whose config sources the
//! developer's real one first.

use crate::tasks::Ctx;
use anyhow::Result;
use std::path::Path;

pub fn config(user_config_dir: &Path, banner: &str) -> String {
    format!(
        r#"# Generated by riabuild. Edits here are overwritten.
#
# XDG_CONFIG_HOME is redirected for this session, so the developer's own fish
# configuration is sourced explicitly before riabuild adds anything.

if test -f "{user}/fish/config.fish"
    source "{user}/fish/config.fish"
end

{banner}
"#,
        user = user_config_dir.display(),
    )
}

pub fn banner_command(text: &str) -> String {
    format!("echo {}", shell_quote(text))
}

fn shell_quote(text: &str) -> String {
    format!("'{}'", text.replace('\'', r"\'"))
}

pub async fn prepare(ctx: &Ctx) -> Result<super::ShellLaunch> {
    let root = ctx.paths.shell_dir("fish");
    let fish_dir = root.join("fish");
    tokio::fs::create_dir_all(&fish_dir).await?;

    let user_config_dir = std::env::var("XDG_CONFIG_HOME")
        .map(std::path::PathBuf::from)
        .unwrap_or_else(|_| ctx.paths.home().join(".config"));

    tokio::fs::write(
        fish_dir.join("config.fish"),
        config(&user_config_dir, &banner_command(super::BANNER)),
    )
    .await?;

    Ok((
        vec!["-i".to_string()],
        vec![(
            "XDG_CONFIG_HOME".to_string(),
            root.to_string_lossy().into_owned(),
        )],
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sources_the_developers_fish_config_first() {
        let generated = config(Path::new("/Users/ada/.config"), "echo hi");
        let source_line = generated.find("source \"/Users/ada/.config/fish/config.fish\"");
        let banner_line = generated.find("echo hi").unwrap();
        assert!(source_line.unwrap() < banner_line, "{generated}");
    }

    #[test]
    fn guards_against_a_missing_user_config() {
        let generated = config(Path::new("/Users/ada/.config"), "");
        assert!(generated.contains("if test -f"));
        assert!(generated.contains("end"));
    }
}
