//! fish reads `$XDG_CONFIG_HOME/fish/config.fish`, so riabuild points
//! `XDG_CONFIG_HOME` at a directory of its own whose config sources the
//! developer's real one first.

use crate::tasks::Ctx;
use anyhow::Result;
use std::path::Path;

pub fn config(user_config_dir: &Path, banner: &str, prompt: &str) -> String {
    format!(
        r#"# Generated by riabuild. Edits here are overwritten.
#
# XDG_CONFIG_HOME is redirected for this session, so the developer's own fish
# configuration is sourced explicitly before riabuild adds anything.

if test -f "{user}/fish/config.fish"
    source "{user}/fish/config.fish"
end

{prompt}

{banner}
"#,
        user = user_config_dir.display(),
    )
}

pub fn banner_command(text: &str) -> String {
    format!("echo {}", shell_quote(text))
}

/// Wraps the developer's `fish_prompt` instead of replacing it.
///
/// fish builds its prompt from a function rather than a variable, so there is
/// nothing to prepend to — the existing function is copied aside and called
/// from a new one that prints the prefix first. That also means fish needs no
/// per-render hook: the wrapper *is* the prompt.
///
/// The `_riabuild_inner_prompt` guard is load-bearing. Sourcing this file twice
/// without it would copy the wrapper onto itself, and the prompt would recurse
/// until fish gave up.
pub fn prompt_command(colour: bool) -> String {
    let prefix = if colour {
        format!(
            "set_color --bold blue\n    echo -n '{}'\n    set_color normal\n    echo -n ' '",
            super::PROMPT_LABEL
        )
    } else {
        format!("echo -n '{} '", super::PROMPT_LABEL)
    };
    format!(
        r#"if not functions -q _riabuild_inner_prompt
    if functions -q fish_prompt
        functions --copy fish_prompt _riabuild_inner_prompt
    else
        function _riabuild_inner_prompt
            echo -n '> '
        end
    end
end

function fish_prompt
    {prefix}
    _riabuild_inner_prompt
end"#
    )
}

fn shell_quote(text: &str) -> String {
    format!("'{}'", text.replace('\'', r"\'"))
}

pub fn prepare(ctx: &Ctx) -> Result<super::ShellLaunch> {
    let root = ctx.paths.shell_dir("fish");
    let fish_dir = root.join("fish");
    std::fs::create_dir_all(&fish_dir)?;

    let user_config_dir = std::env::var("XDG_CONFIG_HOME")
        .map(std::path::PathBuf::from)
        .unwrap_or_else(|_| ctx.paths.home().join(".config"));

    let colour = ctx.ui.colour();
    std::fs::write(
        fish_dir.join("config.fish"),
        config(
            &user_config_dir,
            &banner_command(&super::banner(colour)),
            &prompt_command(colour),
        ),
    )?;

    Ok((
        vec!["-i".to_string()],
        vec![(
            "XDG_CONFIG_HOME".to_string(),
            root.to_string_lossy().into_owned(),
        )],
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sources_the_developers_fish_config_first() {
        let generated = config(Path::new("/Users/ada/.config"), "echo hi", "# prompt");
        let source_line = generated
            .find("source \"/Users/ada/.config/fish/config.fish\"")
            .unwrap();
        let banner_line = generated.find("echo hi").unwrap();
        assert!(source_line < banner_line, "{generated}");
        // The wrapper has to be defined after their fish_prompt exists, or
        // there would be nothing to copy aside.
        assert!(
            source_line < generated.find("# prompt").unwrap(),
            "{generated}"
        );
    }

    #[test]
    fn guards_against_a_missing_user_config() {
        let generated = config(Path::new("/Users/ada/.config"), "", "");
        assert!(generated.contains("if test -f"));
        assert!(generated.contains("end"));
    }

    #[test]
    fn the_developers_prompt_is_wrapped_not_replaced() {
        let generated = prompt_command(true);
        assert!(
            generated.contains("functions --copy fish_prompt _riabuild_inner_prompt"),
            "{generated}"
        );
        assert!(
            generated.contains("_riabuild_inner_prompt\nend"),
            "{generated}"
        );
    }

    #[test]
    fn re_sourcing_cannot_make_the_prompt_recurse() {
        // Without this guard the second source copies riabuild's own wrapper
        // into _riabuild_inner_prompt, and the prompt calls itself forever.
        let generated = prompt_command(true);
        assert!(
            generated.contains("if not functions -q _riabuild_inner_prompt"),
            "{generated}"
        );
    }

    #[test]
    fn a_developer_with_no_prompt_function_still_gets_one() {
        let generated = prompt_command(false);
        assert!(
            generated.contains("function _riabuild_inner_prompt"),
            "{generated}"
        );
        assert!(generated.contains("echo -n '(riabuild) '"), "{generated}");
    }
}
