//! zsh has no `--rcfile`, so riabuild points `ZDOTDIR` at a directory of its
//! own. That directory's `.zshrc` **sources the developer's real `.zshrc`
//! first**, then applies riabuild's environment on top.

use crate::tasks::Ctx;
use anyhow::Result;
use std::path::Path;

/// Generates the `.zshrc` riabuild's `ZDOTDIR` will be read from.
pub fn rcfile(user_zdotdir: &Path, banner: &str, prompt: &str) -> String {
    format!(
        r#"# Generated by riabuild. Edits here are overwritten.
#
# The developer's own configuration is sourced first so their prompt, aliases
# and history settings survive. riabuild only adds on top.

export ZDOTDIR="{user}"
[ -f "$ZDOTDIR/.zshrc" ] && source "$ZDOTDIR/.zshrc"

# riabuild's own environment is exported into this shell by the parent process,
# so nothing needs re-exporting here.
{prompt}

{banner}
"#,
        user = user_zdotdir.display(),
    )
}

/// The line printed when the environment shell starts.
///
/// `-r` rather than `-P`: the text carries raw ANSI escapes, and prompt
/// expansion would try to read `%` sequences inside them.
pub fn banner_command(text: &str) -> String {
    format!("print -r -- {}", shell_quote(text))
}

/// Prefixes the prompt through a `precmd` hook rather than assigning `PROMPT`
/// once.
///
/// powerlevel10k, starship and the oh-my-zsh themes all rebuild `PROMPT` before
/// every render, so a one-time prepend would survive exactly one command.
/// `add-zsh-hook` appends, so riabuild's hook runs after theirs and gets the
/// last word. The guard makes the hook idempotent — without it the prefix
/// stacks up once per prompt on a theme that does not rebuild.
///
/// Colour uses zsh's own `%F`/`%B` prompt escapes rather than raw ANSI, because
/// zsh discounts those from the prompt's width. Raw escapes would make zsh
/// mismeasure the line and corrupt editing of long commands.
pub fn prompt_command(colour: bool) -> String {
    let prefix = if colour {
        format!("%F{{blue}}%B{}%b%f ", super::PROMPT_LABEL)
    } else {
        format!("{} ", super::PROMPT_LABEL)
    };
    format!(
        r#"autoload -Uz add-zsh-hook
_riabuild_prefix={prefix}
_riabuild_prompt() {{
    [[ $PROMPT == "$_riabuild_prefix"* ]] || PROMPT="$_riabuild_prefix$PROMPT"
}}
add-zsh-hook precmd _riabuild_prompt"#,
        prefix = shell_quote(&prefix),
    )
}

fn shell_quote(text: &str) -> String {
    format!("'{}'", text.replace('\'', r"'\''"))
}

pub fn prepare(ctx: &Ctx) -> Result<super::ShellLaunch> {
    let dir = ctx.paths.shell_dir("zsh");
    std::fs::create_dir_all(&dir)?;

    // Respect a developer who already moved their zsh config somewhere else.
    let user_zdotdir = std::env::var("ZDOTDIR")
        .map(std::path::PathBuf::from)
        .unwrap_or_else(|_| ctx.paths.home());

    let colour = ctx.ui.colour();
    std::fs::write(
        dir.join(".zshrc"),
        rcfile(
            &user_zdotdir,
            &banner_command(&super::banner(colour)),
            &prompt_command(colour),
        ),
    )?;

    Ok((
        vec!["-i".to_string()],
        vec![("ZDOTDIR".to_string(), dir.to_string_lossy().into_owned())],
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sources_the_developers_own_config_before_anything_else() {
        let generated = rcfile(Path::new("/Users/ada"), "print hi", "# prompt");
        let source_line = generated.find("source \"$ZDOTDIR/.zshrc\"").unwrap();
        let banner_line = generated.find("print hi").unwrap();
        assert!(
            source_line < banner_line,
            "the developer's config must be sourced first:\n{generated}"
        );
        assert!(generated.contains(r#"export ZDOTDIR="/Users/ada""#));
    }

    #[test]
    fn the_prompt_hook_is_installed_after_the_developers_config() {
        // Registering the hook before their config runs would let a theme that
        // replaces `precmd_functions` wholesale drop it.
        let generated = rcfile(Path::new("/Users/ada"), "print hi", "# prompt");
        let source_line = generated.find("source \"$ZDOTDIR/.zshrc\"").unwrap();
        assert!(
            source_line < generated.find("# prompt").unwrap(),
            "{generated}"
        );
    }

    #[test]
    fn a_missing_user_zshrc_does_not_break_the_shell() {
        // `[ -f ... ] &&` rather than a bare source: a developer with no .zshrc
        // must still get a working shell.
        let generated = rcfile(Path::new("/Users/ada"), "print hi", "# prompt");
        assert!(generated.contains(r#"[ -f "$ZDOTDIR/.zshrc" ]"#));
    }

    #[test]
    fn the_prompt_prefix_is_applied_on_every_render_and_only_once() {
        let generated = prompt_command(true);
        assert!(
            generated.contains("add-zsh-hook precmd _riabuild_prompt"),
            "{generated}"
        );
        // The guard is what keeps a static prompt from growing a new prefix per
        // command.
        assert!(
            generated.contains(r#"[[ $PROMPT == "$_riabuild_prefix"* ]] ||"#),
            "{generated}"
        );
    }

    #[test]
    fn colour_uses_zsh_prompt_escapes_not_raw_ansi() {
        // Raw ANSI in PROMPT makes zsh mismeasure the line and corrupt editing.
        let coloured = prompt_command(true);
        assert!(coloured.contains("%F{blue}%B(riabuild)%b%f"), "{coloured}");
        assert!(!coloured.contains('\x1b'), "{coloured:?}");

        let plain = prompt_command(false);
        assert!(plain.contains("_riabuild_prefix='(riabuild) '"), "{plain}");
    }

    #[test]
    fn banner_text_is_quoted() {
        let command = banner_command("it's active");
        assert!(command.contains(r"'\''"), "{command}");
    }
}
