//! zsh has no `--rcfile`, so riabuild points `ZDOTDIR` at a directory of its
//! own. That directory's `.zshrc` **sources the developer's real `.zshrc`
//! first**, then applies riabuild's environment on top.

use crate::tasks::Ctx;
use anyhow::Result;
use std::path::Path;

/// Generates the `.zshrc` riabuild's `ZDOTDIR` will be read from.
pub fn rcfile(user_zdotdir: &Path, banner: &str) -> String {
    format!(
        r#"# Generated by riabuild. Edits here are overwritten.
#
# The developer's own configuration is sourced first so their prompt, aliases
# and history settings survive. riabuild only adds on top.

export ZDOTDIR="{user}"
[ -f "$ZDOTDIR/.zshrc" ] && source "$ZDOTDIR/.zshrc"

# riabuild's own environment is exported into this shell by the parent process,
# so nothing needs re-exporting here.
{banner}
"#,
        user = user_zdotdir.display(),
    )
}

/// The line printed when the environment shell starts.
pub fn banner_command(text: &str) -> String {
    format!("print -P {}", shell_quote(text))
}

fn shell_quote(text: &str) -> String {
    format!("'{}'", text.replace('\'', r"'\''"))
}

pub fn prepare(ctx: &Ctx) -> Result<super::ShellLaunch> {
    let dir = ctx.paths.shell_dir("zsh");
    std::fs::create_dir_all(&dir)?;

    // Respect a developer who already moved their zsh config somewhere else.
    let user_zdotdir = std::env::var("ZDOTDIR")
        .map(std::path::PathBuf::from)
        .unwrap_or_else(|_| ctx.paths.home());

    std::fs::write(
        dir.join(".zshrc"),
        rcfile(&user_zdotdir, &banner_command(super::BANNER)),
    )?;

    Ok((
        vec!["-i".to_string()],
        vec![("ZDOTDIR".to_string(), dir.to_string_lossy().into_owned())],
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sources_the_developers_own_config_before_anything_else() {
        let generated = rcfile(Path::new("/Users/ada"), "print hi");
        let source_line = generated.find("source \"$ZDOTDIR/.zshrc\"").unwrap();
        let banner_line = generated.find("print hi").unwrap();
        assert!(
            source_line < banner_line,
            "the developer's config must be sourced first:\n{generated}"
        );
        assert!(generated.contains(r#"export ZDOTDIR="/Users/ada""#));
    }

    #[test]
    fn a_missing_user_zshrc_does_not_break_the_shell() {
        // `[ -f ... ] &&` rather than a bare source: a developer with no .zshrc
        // must still get a working shell.
        let generated = rcfile(Path::new("/Users/ada"), "print hi");
        assert!(generated.contains(r#"[ -f "$ZDOTDIR/.zshrc" ]"#));
    }

    #[test]
    fn banner_text_is_quoted() {
        let command = banner_command("it's active");
        assert!(command.contains(r"'\''"), "{command}");
    }
}
