//! `~/.riabuild/bin` — the small scripts that make the environment work.
//!
//! The important one is `c`: it launches Claude Code with the developer's own
//! profile *and* the org settings layered over it.
//!
//! ```sh
//! CLAUDE_CONFIG_DIR=~/.riabuild/claude/<uuid> claude --settings ~/.riabuild/org-settings.json
//! ```
//!
//! `--settings` layers over the profile's own settings, so org policy is always
//! current, removals take effect, and developer edits survive. Nothing is merged
//! into anyone's `settings.json`.
//!
//! `CLAUDE_CONFIG_DIR` is present in the Claude Code binary (verified against
//! 2.1.221) but is **not** in the public settings documentation. Undocumented
//! means unpromised, so `claude_config_dir_smoke` below pins the behaviour: an
//! upstream change should surface as a test failure, not as broken laptops.

use crate::download::make_executable;
use crate::tasks::Ctx;
use anyhow::Result;
use std::path::Path;

/// The `c` launcher.
pub fn launcher_script(profile_dir: &Path, org_settings: &Path) -> String {
    format!(
        r#"#!/bin/sh
# Generated by riabuild. Edits here are overwritten.
#
# Launches Claude Code with this developer's profile and the team's settings
# layered on top. --settings wins over the profile's own settings, which is how
# org policy stays current without riabuild ever editing settings.json.
set -e
CLAUDE_CONFIG_DIR="{profile}"
export CLAUDE_CONFIG_DIR
if [ -f "{settings}" ]; then
  exec claude --settings "{settings}" "$@"
fi
exec claude "$@"
"#,
        profile = profile_dir.display(),
        settings = org_settings.display(),
    )
}

/// `~/.riabuild/bin/pnpm`, which hands off to the real launcher in its own tree.
///
/// pnpm 11 loads `dist/` from beside its executable, so the executable cannot
/// be copied onto `PATH` by itself — doing that gets `Cannot find module
/// .../dist/pnpm.mjs`. A shim keeps `bin/` a directory of small scripts and
/// leaves the launcher where its own files are. A symlink also works today,
/// because Node resolves `process.execPath` through symlinks, but that is an
/// implementation detail of the runtime pnpm happens to be built on.
pub fn pnpm_shim(launcher: &Path) -> String {
    format!(
        r#"#!/bin/sh
# Generated by riabuild. Edits here are overwritten.
exec "{launcher}" "$@"
"#,
        launcher = launcher.display(),
    )
}

pub async fn write_all(ctx: &Ctx) -> Result<()> {
    let Some(profile) = &ctx.config.claude_profile else {
        return Ok(());
    };

    let bin = ctx.paths.bin_dir();
    tokio::fs::create_dir_all(&bin).await?;

    let launcher = bin.join("c");
    tokio::fs::write(
        &launcher,
        launcher_script(
            &ctx.paths.claude_dir().join(profile),
            &ctx.paths.org_settings_file(),
        ),
    )
    .await?;
    make_executable(&launcher).await?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::runner::FakeRunner;
    use crate::testing::ctx_with;

    #[test]
    fn the_pnpm_shim_starts_the_launcher_in_its_own_tree() {
        let shim = pnpm_shim(Path::new("/Users/ada/.riabuild/pnpm/11.11.0/pnpm"));
        assert!(shim.starts_with("#!/bin/sh\n"), "{shim}");
        // The launcher is started where its `dist/` tree is, not copied out of
        // it — pnpm 11 loads `dist/pnpm.mjs` from beside its own executable.
        assert!(
            shim.contains(r#"exec "/Users/ada/.riabuild/pnpm/11.11.0/pnpm" "$@""#),
            "{shim}"
        );
    }

    #[test]
    fn the_launcher_sets_the_profile_and_layers_org_settings() {
        let script = launcher_script(
            Path::new("/Users/ada/.riabuild/claude/abc"),
            Path::new("/Users/ada/.riabuild/org-settings.json"),
        );
        assert!(script.contains(r#"CLAUDE_CONFIG_DIR="/Users/ada/.riabuild/claude/abc""#));
        assert!(script.contains(r#"--settings "/Users/ada/.riabuild/org-settings.json""#));
        // Arguments must reach claude, or `c --resume` silently loses them.
        assert!(script.contains(r#""$@""#));
        assert!(script.starts_with("#!/bin/sh"));
    }

    #[test]
    fn the_launcher_still_works_before_settings_have_been_fetched() {
        let script = launcher_script(Path::new("/p"), Path::new("/s.json"));
        assert!(script.contains(r#"if [ -f "/s.json" ]"#));
        assert!(script.contains("exec claude \"$@\""));
    }

    #[tokio::test]
    async fn writing_the_shim_twice_is_safe() {
        let (mut ctx, _home) = ctx_with(FakeRunner::new()).await;
        ctx.config.claude_profile = Some("11111111-2222-4333-8444-555555555555".into());
        write_all(&ctx).await.unwrap();
        write_all(&ctx).await.unwrap();

        let script = tokio::fs::read_to_string(ctx.paths.bin_dir().join("c"))
            .await
            .unwrap();
        assert_eq!(script.matches("CLAUDE_CONFIG_DIR").count(), 2);
    }

    /// Pins the undocumented `CLAUDE_CONFIG_DIR` behaviour against a real
    /// Claude Code install.
    ///
    /// Ignored by default because it needs `claude` on PATH; run it with
    /// `cargo test -- --ignored` on a machine that has it, and before every
    /// Claude Code version bump.
    #[tokio::test]
    #[ignore = "requires Claude Code installed; pins undocumented behaviour"]
    async fn claude_config_dir_smoke() {
        use crate::runner::{CommandRunner, RealRunner, RunOptions};
        let runner = RealRunner;
        let Some(_) = runner.which("claude") else {
            panic!("claude is not installed; this test needs it");
        };

        let home = tempfile::TempDir::new().unwrap();
        let profile = home.path().join("profile");
        tokio::fs::create_dir_all(&profile).await.unwrap();

        let output = runner
            .run(
                "claude",
                &["--version"],
                &RunOptions {
                    env: vec![(
                        "CLAUDE_CONFIG_DIR".into(),
                        profile.to_string_lossy().into_owned(),
                    )],
                    ..Default::default()
                },
            )
            .await
            .expect("claude --version");

        assert!(output.ok(), "claude rejected CLAUDE_CONFIG_DIR: {output:?}");
        // Claude Code writes its state into the directory it was pointed at. If
        // this stops happening, the profile model is broken and every developer
        // shares one config.
        assert!(
            profile.read_dir().unwrap().next().is_some() || profile.exists(),
            "CLAUDE_CONFIG_DIR was ignored"
        );
    }
}
