//! The shim `SSH_ASKPASS` points at, and the environment that reaches it.
//!
//! `SSH_ASKPASS` names a bare executable path — `ssh` appends the prompt text
//! as `argv[1]`, leaving nowhere to put a subcommand — so riabuild cannot
//! point it at its own binary and must write a shim that execs
//! `riabuild internal askpass`.

use std::path::PathBuf;

use anyhow::Result;
use riabuild_paths::Paths;
use riabuild_runner::RunOptions;
use riabuild_ui::Failure;

use super::{ACCOUNT_VAR, account};
use crate::Remote;

/// The shim `SSH_ASKPASS` points at, rewritten on every run.
///
/// Mode 0700 like every other directory riabuild owns under `~/.riabuild`:
/// this one is only a path to riabuild's own binary, but it is a path `ssh`
/// will execute, and a co-tenant who can write it can answer password prompts
/// on this developer's behalf.
pub async fn ensure_helper(paths: &dyn Paths) -> Result<PathBuf> {
    let binary = std::env::current_exe().map_err(|error| {
        Failure::new(
            "preparing to ask for that server's password",
            "Run `riabuild remote` again from an installed riabuild.",
        )
        .detail(format!("could not locate riabuild's own binary: {error}"))
    })?;

    let dir = paths.ssh_dir();
    let mut builder = tokio::fs::DirBuilder::new();
    builder.recursive(true);
    #[cfg(unix)]
    builder.mode(0o700);
    match builder.create(&dir).await {
        Ok(()) => {}
        Err(error) if error.kind() == std::io::ErrorKind::AlreadyExists => {}
        Err(error) => return Err(error.into()),
    }

    let path = paths.askpass_helper();
    // `exec`, so `ssh` waits on riabuild itself rather than on a shell that
    // outlives it, and the prompt text `ssh` appends is passed through
    // untouched — it is what tells the helper a passphrase from a password.
    tokio::fs::write(
        &path,
        format!(
            "#!/bin/sh\n\
             # Generated by riabuild. Edits here are overwritten.\n\
             exec {} internal askpass \"$@\"\n",
            crate::shell_quote(&binary.to_string_lossy()),
        ),
    )
    .await?;
    make_executable(&path).await?;
    Ok(path)
}

#[cfg(unix)]
async fn make_executable(path: &std::path::Path) -> Result<()> {
    use std::os::unix::fs::PermissionsExt;
    tokio::fs::set_permissions(path, std::fs::Permissions::from_mode(0o700)).await?;
    Ok(())
}

#[cfg(not(unix))]
async fn make_executable(_path: &std::path::Path) -> Result<()> {
    Ok(())
}

/// The environment every `ssh`, `mosh` and `ssh-copy-id` riabuild starts for
/// a server carries.
///
/// `SSH_ASKPASS_REQUIRE=force` is what makes `ssh` consult the helper even
/// though a terminal exists — without it, askpass is reached only when there
/// is no tty *and* `DISPLAY` is set, which is neither of riabuild's cases. It
/// needs OpenSSH 8.4 (2020) or newer; older clients ignore the variable
/// entirely and prompt on the terminal themselves, which is exactly today's
/// behaviour, so an old `ssh` degrades rather than breaks.
pub fn ssh_env(remote: &Remote, paths: &dyn Paths) -> Vec<(String, String)> {
    vec![
        (
            "SSH_ASKPASS".to_string(),
            paths.askpass_helper().to_string_lossy().into_owned(),
        ),
        ("SSH_ASKPASS_REQUIRE".to_string(), "force".to_string()),
        (ACCOUNT_VAR.to_string(), account(remote)),
    ]
}

/// [`ssh_env`] as a ready-made [`RunOptions`], which is what almost every
/// caller wants. Sites that also pipe stdin build
/// `RunOptions { stdin: Some(…), ..run_options(remote, paths) }`.
pub fn run_options(remote: &Remote, paths: &dyn Paths) -> RunOptions {
    RunOptions {
        env: ssh_env(remote, paths),
        ..Default::default()
    }
}
#[cfg(test)]
mod tests {
    use super::*;
    use crate::askpass::remote_fixture as remote;
    use riabuild_paths::RealPaths;

    #[test]
    fn every_ssh_riabuild_starts_names_the_helper_and_the_account() {
        let home = tempfile::TempDir::new().expect("tempdir");
        let paths = RealPaths::rooted_at(home.path());
        let env = ssh_env(&remote(), &paths);
        let value = |key: &str| {
            env.iter()
                .find(|(k, _)| k == key)
                .map(|(_, v)| v.clone())
                .unwrap_or_default()
        };

        assert_eq!(
            value("SSH_ASKPASS"),
            paths.askpass_helper().to_string_lossy()
        );
        // Without `force`, `ssh` reaches the helper only when there is no tty
        // and `DISPLAY` is set — neither of which is riabuild's case, so the
        // helper would never run and every hop would prompt again.
        assert_eq!(value("SSH_ASKPASS_REQUIRE"), "force");
        assert_eq!(value(ACCOUNT_VAR), account(&remote()));
        // The password itself is never one of these: an environment is
        // readable through /proc/<pid>/environ.
        assert!(
            env.iter().all(|(_, v)| !v.contains("hunter2")),
            "only the account name may travel in the environment"
        );
    }

    #[tokio::test]
    async fn the_helper_is_executable_and_execs_riabuilds_own_binary() {
        use std::os::unix::fs::PermissionsExt;

        let home = tempfile::TempDir::new().expect("tempdir");
        let paths = RealPaths::rooted_at(home.path());

        let path = ensure_helper(&paths).await.expect("writes the helper");
        let script = tokio::fs::read_to_string(&path).await.expect("read");

        assert!(script.starts_with("#!/bin/sh\n"), "{script}");
        assert!(script.contains("internal askpass"), "{script}");
        // `"$@"` is what forwards the prompt text `ssh` appends — the helper
        // reads it to tell a key passphrase from an account password, and a
        // shim that dropped it would save the developer's own key passphrase
        // into the keychain as though it were the server's password.
        assert!(script.contains("\"$@\""), "{script}");
        assert!(script.trim_end().ends_with("\"$@\""), "{script}");

        let mode = tokio::fs::metadata(&path)
            .await
            .expect("stat")
            .permissions()
            .mode()
            & 0o777;
        assert_eq!(mode, 0o700, "ssh must be able to execute it, nobody else");
    }

    #[tokio::test]
    async fn a_helper_from_an_older_run_is_rewritten_not_left_alone() {
        // riabuild moves: a Homebrew upgrade, an apt upgrade, a `cargo build`
        // in a worktree. A shim written once and then trusted points at a
        // binary that is no longer there, and `ssh` answers every password
        // prompt with nothing at all.
        let home = tempfile::TempDir::new().expect("tempdir");
        let paths = RealPaths::rooted_at(home.path());
        tokio::fs::create_dir_all(paths.ssh_dir())
            .await
            .expect("mkdir");
        tokio::fs::write(paths.askpass_helper(), "#!/bin/sh\nexec /gone/riabuild\n")
            .await
            .expect("write a stale shim");

        ensure_helper(&paths).await.expect("rewrites it");

        let script = tokio::fs::read_to_string(paths.askpass_helper())
            .await
            .expect("read");
        assert!(!script.contains("/gone/riabuild"), "{script}");
        assert!(script.contains("internal askpass"), "{script}");
    }
}
