//! `bash --rcfile` **replaces** the developer's `.bashrc` rather than adding to
//! it, so the generated file sources theirs first.

use crate::Ctx;
use anyhow::Result;
use std::path::Path;

pub fn rcfile(home: &Path, environment: &str, banner: &str, prompt: &str) -> String {
    format!(
        r#"# Generated by riabuild. Edits here are overwritten.
#
# --rcfile replaces ~/.bashrc entirely, so the developer's own configuration is
# sourced first and riabuild only adds on top.

[ -f "{home}/.bashrc" ] && source "{home}/.bashrc"

{environment}

{prompt}

{banner}
"#,
        home = home.display(),
    )
}

/// Guarded on stdout being a terminal — see the note in `zsh::banner_command`.
/// `if` rather than `&&` so a non-terminal shell does not start with a
/// non-zero `$?` for the developer's prompt to report as a failure.
pub fn banner_command(text: &str) -> String {
    format!(
        "if [ -t 1 ]; then printf '%s\\n' {}; fi",
        super::shell_quote(text)
    )
}

/// Prefixes `PS1` from a `PROMPT_COMMAND` hook rather than assigning it once.
///
/// A one-time prepend is undone by anything that rebuilds `PS1` per render —
/// starship, oh-my-bash, a hand-rolled git-branch prompt. Appending to
/// `PROMPT_COMMAND` puts riabuild after whatever the developer installed.
///
/// Two details that are easy to get wrong:
///
/// * `\[` and `\]` mark the colour escapes as zero-width. Without them bash
///   counts them as visible columns and wraps long command lines over
///   themselves.
/// * `PROMPT_COMMAND` is an array in bash 5.1 and later, and a string
///   everywhere else — including the bash 3.2 that ships with macOS. Assigning
///   a string over an array would overwrite the developer's first hook, so the
///   two cases are handled separately.
pub fn prompt_command(colour: bool) -> String {
    let prefix = if colour {
        format!(r"\[\033[1;34m\]{}\[\033[0m\] ", super::PROMPT_LABEL)
    } else {
        format!("{} ", super::PROMPT_LABEL)
    };
    format!(
        r#"_riabuild_prefix={prefix}
_riabuild_prompt() {{
    case "$PS1" in
        "$_riabuild_prefix"*) ;;
        *) PS1="$_riabuild_prefix$PS1" ;;
    esac
}}
case "$(declare -p PROMPT_COMMAND 2>/dev/null)" in
    declare\ -a*|typeset\ -a*) PROMPT_COMMAND+=(_riabuild_prompt) ;;
    *) PROMPT_COMMAND="${{PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}}_riabuild_prompt" ;;
esac"#,
        prefix = super::shell_quote(&prefix),
    )
}

pub async fn prepare(
    ctx: &Ctx,
    prelude: &str,
    env: &[(String, String)],
) -> Result<super::ShellLaunch> {
    let dir = ctx.paths.shell_dir("bash");
    tokio::fs::create_dir_all(&dir).await?;
    let rc = dir.join("rc");
    let colour = ctx.ui.colour();
    tokio::fs::write(
        &rc,
        rcfile(
            &ctx.paths.home(),
            &super::environment_command(env, &super::riabuild_path_dirs(ctx)),
            &banner_command(prelude),
            &prompt_command(colour),
        ),
    )
    .await?;

    Ok((
        vec![
            "--rcfile".to_string(),
            rc.to_string_lossy().into_owned(),
            "-i".to_string(),
        ],
        Vec::new(),
    ))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::accounts::status::{Account, Identity};
    use crate::testing::ctx_with;
    use riabuild_runner::FakeRunner;

    #[tokio::test]
    async fn prepare_writes_the_prelude_into_the_generated_rcfile() {
        // A test that only exercises `rcfile` with a hand-picked literal, like
        // the ones below, cannot catch `prepare` wiring the wrong thing into
        // it. This one calls `prepare` itself and reads back the file it
        // wrote.
        let (ctx, _home) = ctx_with(FakeRunner::new()).await;
        let accounts = vec![Account {
            number: 1,
            id: "id-1".into(),
            identity: Identity::LoggedIn("clubria@proton.me".into()),
        }];
        let prelude = crate::shell::prelude(&accounts, riabuild_theme::Theme::plain(), None);

        prepare(&ctx, &prelude, &[]).await.unwrap();

        let written = tokio::fs::read_to_string(ctx.paths.shell_dir("bash").join("rc"))
            .await
            .unwrap();
        // Distinctive to the box itself, not the banner — this fails if the
        // box is dropped, truncated, or swapped for the banner alone.
        assert!(written.contains("Your Claude Code accounts:"), "{written}");
        assert!(written.contains("clubria@proton.me"), "{written}");
    }

    #[test]
    fn sources_the_developers_bashrc_first() {
        let generated = rcfile(Path::new("/Users/ada"), "", "printf hi", "# prompt");
        let source_line = generated.find("/Users/ada/.bashrc").unwrap();
        let banner_line = generated.find("printf hi").unwrap();
        assert!(source_line < banner_line, "{generated}");
        assert!(
            source_line < generated.find("# prompt").unwrap(),
            "{generated}"
        );
    }

    #[test]
    fn survives_a_developer_with_no_bashrc() {
        assert!(
            rcfile(Path::new("/Users/ada"), "", "", "").contains(r#"[ -f "/Users/ada/.bashrc" ]"#)
        );
    }

    /// The bug this file exists to prevent, in its second form. Sourcing the
    /// developer's `.bashrc` first is what keeps their prompt and aliases — and
    /// it is also what lets `export PATH="$HOME/.local/bin:$PATH"`, the single
    /// most common line in a dotfile, demote riabuild's own `bin/` from the
    /// front. Everything that depends on that directory leading then stops
    /// working with no error: the `claude` launcher, the clipboard shims, and
    /// the `xdg-open` that carries links to the laptop.
    #[test]
    fn riabuilds_environment_is_applied_after_the_developers_bashrc() {
        let generated = rcfile(
            Path::new("/Users/ada"),
            "export RIABUILD_SHELL='1'",
            "printf hi",
            "# prompt",
        );
        let source_line = generated.find("/Users/ada/.bashrc").unwrap();
        let environment_line = generated
            .find("export RIABUILD_SHELL='1'")
            .expect("the environment block belongs in the generated rcfile");
        assert!(source_line < environment_line, "{generated}");
    }

    #[test]
    fn the_banner_only_prints_to_a_terminal() {
        let command = banner_command("hi");
        assert!(command.starts_with("if [ -t 1 ]; then "), "{command}");
        assert!(command.ends_with("; fi"), "{command}");
    }

    #[test]
    fn colour_escapes_are_marked_zero_width() {
        // Unmarked escapes make bash mismeasure the prompt, and typing past the
        // terminal width starts overwriting the line.
        let coloured = prompt_command(true);
        assert!(
            coloured.contains(r"\[\033[1;34m\](riabuild)\[\033[0m\]"),
            "{coloured}"
        );
    }

    #[test]
    fn no_colour_means_no_escapes_at_all() {
        let plain = prompt_command(false);
        assert!(plain.contains("_riabuild_prefix='(riabuild) '"), "{plain}");
        assert!(!plain.contains(r"\033"), "{plain}");
    }

    #[test]
    fn the_prefix_is_applied_once_and_appended_after_the_developers_hook() {
        let generated = prompt_command(true);
        assert!(
            generated.contains(r#""$_riabuild_prefix"*) ;;"#),
            "{generated}"
        );
        // Existing PROMPT_COMMAND is preserved and riabuild goes last.
        assert!(
            generated.contains(r#"${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}_riabuild_prompt"#),
            "{generated}"
        );
    }

    #[test]
    fn an_array_prompt_command_is_appended_to_rather_than_replaced() {
        // bash 5.1+ makes PROMPT_COMMAND an array; assigning a string to it
        // would clobber the developer's first hook.
        let generated = prompt_command(true);
        assert!(
            generated.contains("PROMPT_COMMAND+=(_riabuild_prompt)"),
            "{generated}"
        );
    }
}
