//! riabuild's own `ssh-copy-id`: the key goes into `authorized_keys` once.
//!
//! ## Why not `ssh-copy-id`
//!
//! `ssh-copy-id` answers "is this key already installed?" by *trying to log
//! in with it* — `attempting to log in with the new key(s), to filter out any
//! that are already installed`. That is the same question
//! [`super::can_sign_in`] asks one call earlier, so on a server that does not
//! honour `authorized_keys` at all, both answers are no and both stay no.
//! Every `riabuild remote` therefore reached the copy step, and every copy
//! step appended another identical line: a developer connecting daily
//! collected a line a day, and nothing riabuild printed suggested it.
//!
//! The question that still has an answer on such a server is a different one:
//! **is the line in the file?** That is content, not authentication, so it is
//! decided on the server by `grep` rather than on this side by a login probe.
//!
//! ## What it will and will not do
//!
//! It appends, or it does nothing. No branch here removes a line from a
//! developer's `authorized_keys` — not even the duplicates an older riabuild
//! left behind, which stay until a human deletes them. `remote forget` is the
//! one command that takes a line back out, it does so by the member id it is
//! forgetting, and this is deliberately not a second place where lines can
//! disappear.
//!
//! ## What identifies the key
//!
//! The base64 body, not the whole line. A comment is free text — riabuild
//! writes `riabuild <member-id> <user>@<host>:<port>` into it, and both the
//! member id and the port can change while the key does not — and an
//! `authorized_keys` line may carry an options prefix (`command="…"`,
//! `from="…"`, `restrict`) that an administrator added on purpose. Matching
//! the body finds the key under any of those, so riabuild neither appends a
//! second copy nor, worse, adds an unrestricted copy of a key somebody had
//! deliberately restricted.

use super::Remote;
use crate::{askpass, shell_command, shell_quote, ssh::Ssh};
use anyhow::{Result, anyhow};
use riabuild_paths::Paths;
use riabuild_runner::CommandRunner;
use riabuild_ui::Failure;
use std::sync::Arc;

/// The exit status the server-side script uses for "the key was already
/// there". Distinct from 0 so the caller can tell a copy from a no-op, and
/// clear of 1 and 2, which `grep` and `sh` use for their own failures.
pub(super) const ALREADY_THERE: i32 = 3;

/// What the server did with the key.
#[derive(Debug, PartialEq, Eq, Clone, Copy)]
pub enum Installed {
    /// The line was not in `authorized_keys` and now is.
    Added,
    /// The key was already in the file, so nothing was written.
    AlreadyThere,
}

/// The base64 body of a public key line — the field that *is* the key.
///
/// Refused rather than defaulted when the line is not a public key: the body
/// becomes a `grep -F` pattern, and an empty pattern matches every line in
/// the file. That reads as "already there", so riabuild would install
/// nothing, report the key as present, and do it again on every run.
pub fn key_body(public_key: &str) -> Result<&str> {
    let mut fields = public_key.split_whitespace();
    let kind = fields.next().unwrap_or_default();
    let body = fields.next().unwrap_or_default();
    // A sanity check, not a parser: `ssh-ed25519`, `ssh-rsa`, `ecdsa-sha2-*`
    // and `sk-ssh-ed25519@openssh.com` all pass, and 16 characters is far
    // below any real key body and far above what a truncated file leaves.
    let plausible = kind.contains("ssh-") || kind.starts_with("ecdsa-");
    if !plausible || body.len() < 16 || !body.chars().all(is_base64) {
        return Err(Failure::new(
            "reading riabuild's own public key",
            "Delete it from ~/.riabuild/ssh-identities and run `riabuild remote` \
             again to generate a new one.",
        )
        .detail(format!(
            "`{}` is not an SSH public key line",
            public_key.trim()
        ))
        .into());
    }
    Ok(body)
}

fn is_base64(c: char) -> bool {
    c.is_ascii_alphanumeric() || c == '+' || c == '/' || c == '='
}

/// The `/bin/sh` script the server runs.
///
/// Exits `0` having appended, [`ALREADY_THERE`] having done nothing, or
/// non-zero having failed. Every value it interpolates goes through
/// [`shell_quote`], so a comment carrying a quote or a `$(…)` is inert —
/// which matters because the comment is the one part of the line riabuild
/// does not fully control on a key a developer regenerated by hand.
pub fn script(public_key: &str) -> Result<String> {
    let line = public_key.trim();
    let body = key_body(line)?;
    Ok(format!(
        // `umask 077` before anything is created, so a fresh `.ssh` is 0700
        // and a fresh `authorized_keys` is 0600 rather than whatever the
        // account's umask would have given them — sshd refuses both if others
        // can write them. An *existing* directory or file keeps its mode: it
        // is the account owner's, and repairing it would be riabuild changing
        // something it did not create.
        //
        // The `tail -c 1` line is what stops a file that does not end in a
        // newline from having riabuild's key glued onto its last line. That
        // does not lock riabuild out — its own line would simply be invalid —
        // it locks out whoever owns the line above.
        //
        // The comment filter in front of the `grep -qF` is what stops a
        // *disabled* line reading as an installed one. `grep -qF <body>` is an
        // unanchored substring match over the whole file, so a line somebody
        // commented out — `# ssh-ed25519 <body> old`, which is how an
        // administrator retires a key without deleting it — answered "already
        // there". riabuild then skipped the copy and told the developer their
        // sshd was not honouring `authorized_keys`, for a key that was never
        // in it. sshd ignores those lines, so this has to as well: `#` first
        // on the line, leading whitespace allowed, exactly what sshd skips.
        // The pipeline's status is the second `grep`'s, so an empty file still
        // reads as "not there".
        //
        // `restorecon` for the same reason `ssh-copy-id` runs it: on an
        // SELinux server a `.ssh` created by this script gets a context sshd
        // will not read, and the failure looks exactly like a key that was
        // never installed. Absent on most servers, hence the `command -v`.
        "umask 077\n\
         d=\"$HOME/.ssh\"\n\
         f=\"$d/authorized_keys\"\n\
         mkdir -p \"$d\" || exit 1\n\
         if [ ! -f \"$f\" ]; then : > \"$f\" || exit 1; fi\n\
         if grep -v '^[[:space:]]*#' \"$f\" | grep -qF {body}; then exit {already}; fi\n\
         if [ -s \"$f\" ] && [ -n \"$(tail -c 1 \"$f\")\" ]; then printf '\\n' >> \"$f\" || exit 1; fi\n\
         printf '%s\\n' {line} >> \"$f\" || exit 1\n\
         if command -v restorecon >/dev/null 2>&1; then restorecon -F \"$d\" \"$f\" >/dev/null 2>&1 || true; fi\n\
         exit 0\n",
        body = shell_quote(body),
        line = shell_quote(line),
        already = ALREADY_THERE,
    ))
}

/// Puts riabuild's public key in `~/.ssh/authorized_keys` on the server, if
/// it is not there already.
///
/// One captured `ssh`, not the pty `ssh-copy-id` used to get. `ssh-copy-id`
/// needed a terminal because an OpenSSH older than 8.4 prompts on one;
/// riabuild's own prompt is [`riabuild_ui::secret`], which opens `/dev/tty`
/// directly — precisely so it works when `ssh` has redirected the askpass
/// helper's stdio — so capturing costs nothing and makes stderr available to
/// say *why* a failure failed.
///
/// `every_identity` — no `IdentitiesOnly=yes` — for the reason
/// [`crate::identity::ssh_options`] gives: on the common cloud VM the
/// developer's existing key, or their agent, is what proves who we are while
/// the new key is being installed.
/// `BatchMode` is likewise absent — a password is a legitimate way in here,
/// and this is the one step whose whole job is to make it unnecessary later.
///
/// `entry` is the credential that gets us *in* to do it, and it is the whole
/// of what an issued key changes about this file. `None` is the original
/// behaviour: whatever the developer's own agent or `~/.ssh` offers, and then
/// the account password through `askpass`. `Some` names one identity in
/// riabuild's own agent, which is what makes this step work on a server that
/// has no password to ask for. What the script does, and how it decides
/// whether the line is already there, is identical either way.
pub async fn install_key(
    remote: &Remote,
    paths: &dyn Paths,
    runner: Arc<dyn CommandRunner>,
    public_key: &str,
    entry: Option<&crate::issued::Working>,
) -> Result<Installed> {
    // Before the connection, deliberately: a key that is not a key cannot be
    // installed by any number of round trips, and a `grep` for nothing would
    // come back "already there".
    let script = script(public_key)?;

    // With no issued identity this is the one step that offers the developer's
    // own agent and `~/.ssh` as well — that existing key is often what
    // authorises the new one. With one, `IdentitiesOnly=yes` comes back and is
    // doing work: without it the agent offers every key it holds before this
    // one, and a server with a low `MaxAuthTries` can drop the connection
    // before reaching the key that was just proved to work.
    let mut ssh = Ssh::to(remote, paths, runner.clone()).carry(entry);
    if entry.is_none() {
        ssh = ssh.every_identity();
    }
    let output = ssh.run(&shell_command(&script)).await?;

    // This is the first — and on almost every run the only — `ssh` in remote
    // mode that can be answered by a password the developer types, so it is
    // where what the server made of that password is decided. Nothing riabuild
    // was handed is kept until sshd has taken it, and a refusal clears what was
    // stored rather than leaving it to be replayed at every connection of every
    // future run until the account locks. See `askpass::Slots`.
    //
    // Best effort, both ways: a keyring that will not answer must not turn a
    // key that installed perfectly well into a failed run. The cost of failing
    // to promote is one extra prompt; `answer` has already told the developer
    // if it could not write at all.
    match askpass::verdict(output.code, &output.stderr) {
        askpass::Verdict::Accepted => {
            let _ = askpass::accept(remote, paths, runner.clone()).await;
        }
        askpass::Verdict::Rejected => {
            let _ = askpass::forget(remote, paths, runner.clone()).await;
        }
        askpass::Verdict::Unanswered => {}
    }

    match output.code {
        Some(0) => Ok(Installed::Added),
        Some(ALREADY_THERE) => Ok(Installed::AlreadyThere),
        // Deliberately not a [`Failure`] with a remedy attached: whether this
        // stops the run or becomes a warning beside a password fallback is
        // `authorise`'s decision, and the "add this line to authorized_keys"
        // wording is already `authorise`'s. A remedy written here too would
        // reach the developer twice in one message.
        _ => Err(anyhow!(
            "{}{}",
            output.code.map_or_else(
                || "ssh was killed before it answered".to_string(),
                |code| format!("ssh exited {code}")
            ),
            match output.stderr.trim() {
                "" => String::new(),
                stderr => format!(": {stderr}"),
            }
        )),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::askpass;
    use riabuild_paths::RealPaths;
    use riabuild_runner::{CommandOutput, FakeRunner, RealRunner, RunOptions};

    fn remote() -> Remote {
        Remote {
            name: "build-01".into(),
            host: "build-01.fly.dev".into(),
            port: 2222,
            user: "ada".into(),
        }
    }

    /// A real riabuild key line, comment and all — the shape `ensure_key`
    /// generates, whose comment carries a member id and a login target that
    /// can both change while the key stays the same.
    const KEY: &str = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDQMfwG+m0AkDbU6a0vxE5ktTNTso5LskpebOKYF2VHP riabuild 9544e195 ada@build-01:22";
    const BODY: &str = "AAAAC3NzaC1lZDI1NTE5AAAAIDQMfwG+m0AkDbU6a0vxE5ktTNTso5LskpebOKYF2VHP";

    // ---- what identifies a key -------------------------------------------

    #[test]
    fn a_key_is_identified_by_its_body_not_by_the_line_it_came_on() {
        // The comment is free text and riabuild's own changes with the member
        // id and the port; the body is the key.
        assert_eq!(key_body(KEY).expect("a key"), BODY);
        assert_eq!(
            key_body(&format!("ssh-ed25519 {BODY} someone-elses-comment\n")).expect("a key"),
            BODY
        );
        assert_eq!(
            key_body(&format!("ssh-ed25519 {BODY}")).expect("a key"),
            BODY,
            "a key with no comment at all is still a key"
        );
    }

    #[test]
    fn something_that_is_not_a_public_key_is_refused_rather_than_grepped_for() {
        // The body becomes a `grep -F` pattern. An empty one matches every
        // line in the file, which reads as "already there" — so riabuild
        // would report success having installed nothing, on every run,
        // forever.
        for not_a_key in [
            "",
            "\n",
            "ssh-ed25519",
            "ssh-ed25519 AAAA",
            "-----BEGIN OPENSSH PRIVATE KEY-----",
            "# a comment someone left in the file",
        ] {
            assert!(
                key_body(not_a_key).is_err(),
                "must not be read as a key: {not_a_key:?}"
            );
        }
    }

    // ---- the script, run for real ----------------------------------------

    /// Runs the server-side script the way a server would: `/bin/sh`, with
    /// `HOME` pointed at a directory this test owns.
    ///
    /// Through `RealRunner` rather than `std::process`, which this workspace
    /// allows nowhere outside `riabuild-runner` — and the script is the one
    /// part of this file that a string assertion cannot check. `grep -qF`
    /// against a body containing `+` and `/`, `tail -c 1` on a file with no
    /// trailing newline, `umask` reaching `mkdir -p`: each is a real shell
    /// behaviour, and a test that only inspected the generated text would
    /// agree with whatever the generator happened to emit.
    async fn run_on(home: &std::path::Path, public_key: &str) -> CommandOutput {
        let runner = RealRunner;
        runner
            .run(
                "/bin/sh",
                &["-c", &script(public_key).expect("a script")],
                &RunOptions {
                    env: vec![("HOME".to_string(), home.to_string_lossy().into_owned())],
                    ..Default::default()
                },
            )
            .await
            .expect("sh runs")
    }

    async fn authorized_keys(home: &std::path::Path) -> String {
        tokio::fs::read_to_string(home.join(".ssh/authorized_keys"))
            .await
            .expect("authorized_keys")
    }

    async fn seed(home: &std::path::Path, contents: &str) {
        tokio::fs::create_dir_all(home.join(".ssh"))
            .await
            .expect("mkdir");
        tokio::fs::write(home.join(".ssh/authorized_keys"), contents)
            .await
            .expect("write");
    }

    #[cfg(unix)]
    #[tokio::test]
    async fn a_key_that_is_already_there_is_not_added_a_second_time() {
        // The reported bug, reproduced against a real shell: a server that
        // never honours the key means riabuild reaches this step on every
        // single run, so this script running twice has to leave one line.
        let home = tempfile::TempDir::new().expect("tempdir");

        let first = run_on(home.path(), KEY).await;
        assert_eq!(first.code, Some(0), "{}", first.stderr);
        let second = run_on(home.path(), KEY).await;
        assert_eq!(
            second.code,
            Some(3),
            "the second run has to report the key was already there: {}",
            second.stderr
        );
        let third = run_on(home.path(), KEY).await;
        assert_eq!(third.code, Some(3), "{}", third.stderr);

        let file = authorized_keys(home.path()).await;
        assert_eq!(
            file.lines().filter(|line| line.contains(BODY)).count(),
            1,
            "three runs, one line: {file:?}"
        );
    }

    #[cfg(unix)]
    #[tokio::test]
    async fn a_key_already_there_under_a_different_comment_is_still_there() {
        // riabuild's own comment carries the member id and the login target,
        // both of which change without the key changing — and a developer may
        // have pasted the key by hand, which is exactly what the warning this
        // step falls back to tells them to do.
        let home = tempfile::TempDir::new().expect("tempdir");
        seed(home.path(), &format!("ssh-ed25519 {BODY} pasted-by-hand\n")).await;

        let output = run_on(home.path(), KEY).await;

        assert_eq!(output.code, Some(3), "{}", output.stderr);
        assert_eq!(
            authorized_keys(home.path()).await,
            format!("ssh-ed25519 {BODY} pasted-by-hand\n"),
            "the file must be untouched"
        );
    }

    #[cfg(unix)]
    #[tokio::test]
    async fn a_key_carrying_restrictions_is_not_duplicated_without_them() {
        // An administrator's `command=`/`from=` prefix is a deliberate
        // restriction. Appending a plain copy of the same key beside it would
        // hand the developer an unrestricted way in — a security hole opened
        // by a convenience feature.
        let home = tempfile::TempDir::new().expect("tempdir");
        let restricted = format!("from=\"10.0.0.0/8\",restrict ssh-ed25519 {BODY} riabuild\n");
        seed(home.path(), &restricted).await;

        let output = run_on(home.path(), KEY).await;

        assert_eq!(output.code, Some(3), "{}", output.stderr);
        assert_eq!(authorized_keys(home.path()).await, restricted);
    }

    #[cfg(unix)]
    #[tokio::test]
    async fn a_file_with_no_trailing_newline_does_not_get_two_keys_on_one_line() {
        // `authorized_keys` files written by hand routinely end without one,
        // and a naive append glues riabuild's key onto the end of somebody
        // else's — which does not lock riabuild out (its line is invalid),
        // it locks *them* out.
        let home = tempfile::TempDir::new().expect("tempdir");
        let existing = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB colleague";
        seed(home.path(), existing).await;

        let output = run_on(home.path(), KEY).await;

        assert_eq!(output.code, Some(0), "{}", output.stderr);
        let file = authorized_keys(home.path()).await;
        let lines: Vec<&str> = file.lines().collect();
        assert_eq!(lines.len(), 2, "{file:?}");
        assert_eq!(lines[0], existing, "the colleague's key must survive whole");
        assert_eq!(lines[1], KEY);
    }

    #[cfg(unix)]
    #[tokio::test]
    async fn nothing_already_in_the_file_is_ever_removed() {
        // Including the duplicates an older riabuild left behind: this step
        // appends or does nothing, and `remote forget` is the only command
        // that takes a line back out.
        let home = tempfile::TempDir::new().expect("tempdir");
        let pile =
            format!("{KEY}\n{KEY}\n{KEY}\nssh-rsa AAAAB3NzaC1yc2EAAAA-colleague colleague\n");
        seed(home.path(), &pile).await;

        let output = run_on(home.path(), KEY).await;

        assert_eq!(output.code, Some(3), "{}", output.stderr);
        assert_eq!(
            authorized_keys(home.path()).await,
            pile,
            "riabuild must not tidy a file it was only asked to add to"
        );
    }

    #[cfg(unix)]
    #[tokio::test]
    async fn a_key_that_is_only_there_as_a_comment_is_not_there() {
        // I046. `grep -qF <body>` is an unanchored substring match over the
        // whole file, comments included, so a line an administrator had
        // *retired* — the ordinary way to take a key out without deleting it —
        // answered "already there". riabuild then skipped the copy and told
        // the developer their sshd was not honouring `authorized_keys`, for a
        // key that had never been in it and never would be. sshd ignores those
        // lines; so must this.
        let home = tempfile::TempDir::new().expect("tempdir");
        let retired = format!(
            "# ssh-ed25519 {BODY} riabuild retired-2026-07\n   #  ssh-ed25519 {BODY} indented\n"
        );
        seed(home.path(), &retired).await;

        let output = run_on(home.path(), KEY).await;

        assert_eq!(
            output.code,
            Some(0),
            "a commented-out line is not an installed key: {}",
            output.stderr
        );
        let file = authorized_keys(home.path()).await;
        let lines: Vec<&str> = file.lines().collect();
        assert_eq!(lines.len(), 3, "{file:?}");
        assert_eq!(
            lines[0],
            "# ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDQMfwG+m0AkDbU6a0vxE5ktTNTso5LskpebOKYF2VHP riabuild retired-2026-07",
            "and the retired lines are still nobody's to delete but the account owner's: {file:?}"
        );
        assert_eq!(lines[2], KEY);

        // Idempotence survives it: the line riabuild just added is a real one,
        // so a second run still reports it as already there rather than
        // appending a line a day.
        let second = run_on(home.path(), KEY).await;
        assert_eq!(second.code, Some(3), "{}", second.stderr);
        assert_eq!(
            authorized_keys(home.path())
                .await
                .lines()
                .filter(|line| line.contains(BODY))
                .count(),
            3,
            "two comments and exactly one key"
        );
    }

    // ---- what the server made of the password -----------------------------

    /// The keychain CLI of both platforms, so the assertion below reads the
    /// same on a Mac and on Linux — `forget`'s own test does this for the same
    /// reason. Which of the two riabuild reaches for is
    /// `keychain::select_password_store`'s decision and not this file's.
    fn keychain_delete(call: &str) -> bool {
        call.starts_with("security delete-generic-password")
            || call.starts_with("secret-tool clear")
    }

    fn copy_runner(code: i32, stderr: &str) -> Arc<FakeRunner> {
        Arc::new(
            FakeRunner::new()
                .with("ssh", code, "", stderr)
                .with("security", 0, "", "")
                .with("secret-tool", 0, "", ""),
        )
    }

    #[tokio::test]
    async fn a_password_the_server_refuses_is_forgotten_rather_than_replayed() {
        // I036's other half, at the one connection that can observe it. Until
        // this existed nothing anywhere called `askpass::forget` except
        // `remote forget`, so a password sshd had just refused stayed in the
        // keychain and was offered again at every connection of every future
        // run — which is how an account gets locked out by a typo.
        let home = tempfile::TempDir::new().expect("tempdir");
        let paths = RealPaths::rooted_at(home.path());
        let fake = copy_runner(
            255,
            "ada@build-01.fly.dev: Permission denied (publickey,password).",
        );

        let error = install_key(&remote(), &paths, fake.clone(), KEY, None)
            .await
            .expect_err("a refused connection installs nothing");
        assert!(format!("{error}").contains("Permission denied"), "{error}");

        let deletes: Vec<String> = fake
            .calls()
            .into_iter()
            .filter(|call| keychain_delete(call))
            .collect();
        assert!(
            deletes
                .iter()
                .any(|call| call.contains(&askpass::account(&remote()))),
            "the refused password is still in the keychain: {deletes:?}"
        );
    }

    #[tokio::test]
    async fn a_copy_the_server_authenticated_keeps_the_password_it_used() {
        // The complement, and the one that stops the fix above from being
        // "clear it always": nine more connections follow this one, and they
        // are silent only because the password survives.
        let home = tempfile::TempDir::new().expect("tempdir");
        let paths = RealPaths::rooted_at(home.path());
        let fake = copy_runner(0, "");

        assert_eq!(
            install_key(&remote(), &paths, fake.clone(), KEY, None)
                .await
                .expect("installs"),
            Installed::Added
        );

        assert!(
            !fake.calls().iter().any(|call| keychain_delete(call)),
            "a password the server took must not be thrown away: {:?}",
            fake.calls()
        );
    }

    #[tokio::test]
    async fn a_key_the_server_refuses_is_not_a_password_the_server_refuses() {
        // An issued key turned away by a keys-only server says nothing about
        // the account password, and clearing one there would cost the
        // developer a prompt for a secret that is perfectly good.
        let home = tempfile::TempDir::new().expect("tempdir");
        let paths = RealPaths::rooted_at(home.path());
        let fake = copy_runner(255, "ada@build-01.fly.dev: Permission denied (publickey).");

        install_key(&remote(), &paths, fake.clone(), KEY, None)
            .await
            .expect_err("still a failed copy");

        assert!(
            !fake.calls().iter().any(|call| keychain_delete(call)),
            "{:?}",
            fake.calls()
        );
    }

    #[cfg(unix)]
    #[tokio::test]
    async fn an_account_that_has_never_used_ssh_gets_a_private_directory_and_file() {
        // sshd refuses a key directory or file that others can read, so
        // creating either at the account's umask would install a key that
        // cannot work and say nothing about why.
        use std::os::unix::fs::PermissionsExt;

        let home = tempfile::TempDir::new().expect("tempdir");

        let output = run_on(home.path(), KEY).await;
        assert_eq!(output.code, Some(0), "{}", output.stderr);

        let mode = |path: std::path::PathBuf| async move {
            tokio::fs::metadata(path)
                .await
                .expect("stat")
                .permissions()
                .mode()
                & 0o777
        };
        assert_eq!(mode(home.path().join(".ssh")).await, 0o700);
        assert_eq!(mode(home.path().join(".ssh/authorized_keys")).await, 0o600);
    }

    #[cfg(unix)]
    #[tokio::test]
    async fn an_existing_ssh_directory_keeps_the_mode_the_developer_gave_it() {
        // Same rule as `identity::ensure_key`'s directory handling read from
        // the other side: what riabuild creates it locks down, what it finds
        // is the account owner's business.
        use std::os::unix::fs::PermissionsExt;

        let home = tempfile::TempDir::new().expect("tempdir");
        seed(home.path(), "").await;
        tokio::fs::set_permissions(
            home.path().join(".ssh"),
            std::fs::Permissions::from_mode(0o755),
        )
        .await
        .expect("chmod");

        run_on(home.path(), KEY).await;

        let mode = tokio::fs::metadata(home.path().join(".ssh"))
            .await
            .expect("stat")
            .permissions()
            .mode()
            & 0o777;
        assert_eq!(
            mode, 0o755,
            "riabuild must not chmod what it did not create"
        );
    }

    #[cfg(unix)]
    #[tokio::test]
    async fn a_comment_full_of_shell_metacharacters_is_inert() {
        // The comment reaches the server inside a `/bin/sh -c` string. A key
        // whose comment contains a quote or a substitution must land in the
        // file verbatim rather than running.
        let home = tempfile::TempDir::new().expect("tempdir");
        let nasty = format!(
            "ssh-ed25519 {BODY} riabuild 'x' $(touch {}/pwned) `id`",
            home.path().display()
        );

        let output = run_on(home.path(), &nasty).await;

        assert_eq!(output.code, Some(0), "{}", output.stderr);
        assert!(
            !home.path().join("pwned").exists(),
            "the comment was executed rather than written"
        );
        assert_eq!(authorized_keys(home.path()).await.trim_end(), nasty);
    }

    // ---- the ssh call around it ------------------------------------------

    /// The invocation `install_key` makes, as `FakeRunner` records it.
    fn the_ssh_call(fake: &FakeRunner) -> String {
        fake.calls()
            .into_iter()
            .find(|call| call.starts_with("ssh "))
            .expect("an ssh call")
    }

    #[tokio::test]
    async fn the_copy_goes_through_riabuilds_pinned_host_key_and_askpass_helper() {
        let home = tempfile::TempDir::new().expect("tempdir");
        let paths = RealPaths::rooted_at(home.path());
        let fake = Arc::new(FakeRunner::new().containing("authorized_keys", 0, "", ""));

        install_key(&remote(), &paths, fake.clone(), KEY, None)
            .await
            .expect("added");

        let call = the_ssh_call(&fake);
        assert!(call.contains("-p 2222"), "{call}");
        assert!(call.contains("-F /dev/null"), "{call}");
        assert!(
            call.contains(&format!(
                "UserKnownHostsFile={}",
                paths.known_hosts_file().to_string_lossy()
            )),
            "the copy must not trust a host afresh: {call}"
        );
        assert!(call.contains("StrictHostKeyChecking=yes"), "{call}");
        // The one step that does *not* pin IdentitiesOnly: on the common
        // cloud VM the developer's existing key or agent is what proves who
        // we are while the new key is being installed.
        assert!(!call.contains("IdentitiesOnly"), "{call}");
        // And it must be able to fall back to a password, which BatchMode
        // forbids outright.
        assert!(!call.contains("BatchMode"), "{call}");

        let env = fake.env_of("ssh");
        for (key, value) in askpass::ssh_env(&remote(), &paths) {
            assert!(
                env.contains(&(key.clone(), value.clone())),
                "the copy lost its askpass helper, so the password is asked for again: {env:?}"
            );
        }
    }

    #[tokio::test]
    async fn the_server_deciding_the_key_is_already_there_is_not_a_failure() {
        let home = tempfile::TempDir::new().expect("tempdir");
        let paths = RealPaths::rooted_at(home.path());
        let fake = Arc::new(FakeRunner::new().containing("authorized_keys", 3, "", ""));

        let installed = install_key(&remote(), &paths, fake, KEY, None)
            .await
            .expect("already there is an outcome, not an error");

        assert_eq!(installed, Installed::AlreadyThere);
    }

    #[tokio::test]
    async fn a_copy_that_actually_failed_says_what_the_server_said() {
        // Distinct from the two above: a read-only home, a full disk, a
        // connection that dropped. It carries no remedy of its own — whether
        // a failure here stops the run or becomes a warning beside a password
        // fallback is `authorise`'s call, and it is `authorise` that owns the
        // "add this line to authorized_keys" wording. Two copies of that
        // instruction in one message is what happens when both layers write
        // one.
        let home = tempfile::TempDir::new().expect("tempdir");
        let paths = RealPaths::rooted_at(home.path());
        let fake = Arc::new(FakeRunner::new().containing(
            "authorized_keys",
            1,
            "",
            "sh: cannot create /home/ada/.ssh/authorized_keys: Read-only file system",
        ));

        let error = install_key(&remote(), &paths, fake, KEY, None)
            .await
            .expect_err("a failed copy must not read as success");

        let said = error.to_string();
        assert!(
            said.contains("Read-only"),
            "the server's own words are the whole diagnostic here: {said}"
        );
        assert!(
            !said.to_lowercase().contains("add this line"),
            "the remedy belongs to the caller: {said}"
        );
    }

    #[tokio::test]
    async fn a_missing_public_key_never_reaches_the_server() {
        let home = tempfile::TempDir::new().expect("tempdir");
        let paths = RealPaths::rooted_at(home.path());
        let fake = Arc::new(FakeRunner::new().containing("authorized_keys", 0, "", ""));

        install_key(&remote(), &paths, fake.clone(), "", None)
            .await
            .expect_err("an empty key is not something to install");

        assert!(
            fake.calls().is_empty(),
            "a grep for nothing matches everything: {:?}",
            fake.calls()
        );
    }
}
