# shellcheck shell=bash
#
# Sourced by e2e/run.sh, in the shell the whole run shares. Not executable:
# every stage reads variables and functions earlier stages left behind, and a
# subshell would lose them. e2e/run.sh names what this one needs.

# ---------------------------------------------------------------------------
# 15. CLAUDE_CONFIG_DIR — undocumented, therefore only true while tested
# ---------------------------------------------------------------------------

step "CLAUDE_CONFIG_DIR still redirects Claude Code"

# Resolved through the PATH riabuild hands the developer rather than guessed at
# a fixed location: whether Claude Code came from riabuild's own npm or was
# already on the machine, the environment is what decides which one a developer
# actually gets, and that is the one worth pinning.
RIABUILD_PATH="$(printf '%s' "$ENV_OUT" | sed -n "s/^export PATH='\(.*\)'$/\1/p" | head -1)"
CLAUDE_BIN="$(PATH="$RIABUILD_PATH" command -v claude 2>/dev/null || true)"

# What PATH finds is riabuild's launcher, and the launcher is the wrong thing to
# ask this question of: it `export`s its own account's CLAUDE_CONFIG_DIR over
# whatever the caller set, so running it with a directory of this script's
# choosing tests the launcher's own `export` and says nothing at all about
# Claude Code. That read as a pass only while there was no launcher to find — a
# run that stopped at the sign-in wrote none, `command -v claude` fell through
# to the Node tarball's copy, and this stage got the raw binary by accident.
# Now that the launchers land whatever the tasks did, the binary has to be asked
# for on purpose.
#
# Taken out of the launcher rather than rebuilt from `$NODE_VERSION` here, for
# the reason the rest of this suite is built on: a path the test works out for
# itself goes on passing the day riabuild's moves. This is the binary the
# developer's own `claude` execs, named by riabuild in the file riabuild wrote.
#
# What the launcher does with it is asserted in stage 11 — that `claude-1` pins
# account 1's directory. The two halves together are the isolation: Claude Code
# honours CLAUDE_CONFIG_DIR, and the launcher sets it per account.
#
# The two are told apart by the banner riabuild puts on everything it generates
# rather than by comparing paths, so that a launcher `bin/` gained under some
# other name is still recognised as one. `head` first, because Claude Code's own
# `cli.js` is tens of megabytes and there is no reason to read it.
case "$(head -3 "$CLAUDE_BIN" 2>/dev/null || true)" in
  *'Generated by riabuild'*)
    # Empty if the launcher stops naming its binary on a line of its own, and
    # deliberately not defaulted to `$CLAUDE_BIN` — that would put the launcher
    # back under test and the failure below is the honest answer.
    CLAUDE_REAL="$(sed -n 's/^claude_binary="\(.*\)"$/\1/p' "$CLAUDE_BIN" | head -1)"
    ;;
  *) CLAUDE_REAL="$CLAUDE_BIN" ;;
esac

if [ -n "$CLAUDE_REAL" ] && [ -x "$CLAUDE_REAL" ]; then
  info "claude: $CLAUDE_BIN -> $CLAUDE_REAL"
  PIN_DIR="$SCRATCH/claude-pin"
  PIN_HOME="$SCRATCH/claude-pin-home"
  mkdir -p "$PIN_DIR" "$PIN_HOME"
  # `config ls` rather than `--version`: reading configuration is what forces
  # Claude Code to decide where its configuration lives, and `--version` answers
  # without touching disk at all.
  env HOME="$PIN_HOME" CLAUDE_CONFIG_DIR="$PIN_DIR" "$CLAUDE_REAL" config ls >/dev/null 2>&1 || true
  if [ -f "$PIN_DIR/.claude.json" ]; then
    pass "Claude Code kept its configuration in CLAUDE_CONFIG_DIR"
    check_missing "and left the home directory alone" \
      "$(ls -A "$PIN_HOME" 2>/dev/null || true)" ".claude"
  else
    # Not a failure of riabuild — a change in Claude Code. Said plainly so
    # whoever reads this knows which repository to go and look at.
    # A failure, not a note. CLAUDE_CONFIG_DIR is undocumented, every per-account
    # launcher depends on it entirely, and an upstream change has to surface
    # here rather than as every developer's accounts quietly merging into one.
    fail "Claude Code did not keep its configuration in CLAUDE_CONFIG_DIR — the per-account launchers' isolation is gone"
  fi
else
  fail "no Claude Code behind the claude on the PATH riabuild provides ($CLAUDE_BIN -> ${CLAUDE_REAL:-nothing}) — the per-account launchers would not work"
fi

