//! `~/.riabuild/bin/codex` — the Codex CLI launcher.
//!
//! The same shape as the Claude Code launcher next door, for the same reasons:
//! a small generated script in `bin/` that pins the config directory riabuild
//! owns, adds the flags the team wants by default, and falls back to `PATH`
//! when the binary it recorded has moved.
//!
//! ```sh
//! CODEX_HOME=~/.riabuild/codex codex --yolo
//! ```
//!
//! Nine of them, `codex-1` … `codex-9`, plus `codex` for the first — because
//! Codex keeps several sign-ins apart exactly the way Claude Code does. Its
//! credentials live in `$CODEX_HOME/auth.json` and nowhere else, so pointing it
//! at nine directories really is nine independent accounts. Verified against
//! 0.147.0: two homes hold two different API keys at the same time, and
//! `codex logout` in one leaves the other logged in.
//!
//! The nine exist from the first run rather than being created on demand.
//! Claude's are made by riabuild's own sign-in flow, which is what gives it
//! something to count; riabuild signs nobody in to Codex, so there is no moment
//! at which it would learn that a developer wants a second one. Nine empty
//! directories cost nothing, and `codex-3 login` then works the first time it
//! is typed instead of failing on a `CODEX_HOME` that is not there.
//!
//! Three things the Claude launcher does are deliberately **not** copied here.
//! `unset SSH_CONNECTION SSH_CLIENT SSH_TTY` and the `WAYLAND_DISPLAY` claim
//! are workarounds for behaviour read out of the Claude Code binary, and the
//! `--settings` layer carries the org's Claude settings; none of the three is a
//! fact about Codex. Asserting them here would be inventing an upstream
//! behaviour rather than accommodating one.

use anyhow::Result;
use riabuild_fetch::archive::make_executable;
use std::path::Path;

/// What `--yolo` is short for, and what the launcher has to look for in the
/// developer's own arguments before adding it.
///
/// Codex rejects the flag twice — "cannot be used multiple times" — so a
/// launcher that always appended it would turn a developer typing the obvious
/// `codex --yolo` into a parser error naming a flag they did not type.
const YOLO_LONG: &str = "--dangerously-bypass-approvals-and-sandbox";

/// How many Codex profiles riabuild makes.
///
/// Nine, for the reason `accounts::MAX` is nine: it keeps every launcher name
/// single digit, so `codex-9` is the last one and `codex-12` is an obvious typo
/// rather than something to interpret. Deliberately its own constant rather
/// than a reference to `accounts::MAX` — the two happen to agree, but a Codex
/// profile and a Claude account are not the same thing, and coupling them would
/// make changing one silently change the other.
pub const PROFILES: usize = 9;

/// The launcher, which is the only thing that names `CODEX_HOME`.
///
/// Not exported into the environment shell, for the reason `CLAUDE_CONFIG_DIR`
/// is not: an exported value follows every `codex` a developer starts by any
/// route, including one they deliberately ran from outside riabuild's tree.
pub fn launcher_script(codex_home: &Path, codex: &str, bin_dir: &Path) -> String {
    format!(
        r#"#!/bin/sh
# Generated by riabuild. Edits here are overwritten.
#
# Launches the Codex CLI against the config directory riabuild owns, with
# approvals and the sandbox bypassed by default.
set -e
CODEX_HOME="{codex_home}"
export CODEX_HOME
# Codex refuses to start against a CODEX_HOME that is not there — "Error finding
# codex home" — rather than creating one, so naming the directory is only half
# of pointing at it. Created here as well as by the `codex_cli` task because the
# gap between two riabuild runs is exactly where a `rm -rf` lands: the task
# would go on reporting a satisfied machine, and every `codex` until the next
# run would refuse to start.
[ -d "$CODEX_HOME" ] || mkdir -p "$CODEX_HOME"
codex_binary="{codex}"
case "$codex_binary" in
  /*) ;;
  # A non-absolute path (no Node pinned yet) can't be trusted with the -x test
  # below: a same-named executable in the current directory would pass it, skip
  # the PATH strip, and exec a bare name that PATH search resolves straight back
  # to this script.
  *) codex_binary="" ;;
esac
if [ ! -x "$codex_binary" ]; then
  # The recorded binary is gone: a `codex update`, or a Node version change
  # since the last run. Fall back to PATH with riabuild's own bin/ removed —
  # without that this script finds itself, because bin/ comes first inside the
  # environment shell.
  PATH=$(printf '%s' "$PATH" | tr ':' '\n' | grep -vxF "{bin_dir}" | paste -sd: -)
  export PATH
  codex_binary=codex
else
  # Codex is a Node script, not a native binary: npm installs bin/codex as a
  # symlink to a codex.js whose shebang is `#!/usr/bin/env node`, so starting
  # it asks PATH for a Node before Codex gets a say. riabuild's own Node sits
  # in the same directory as the binary just tested, and naming it here is what
  # makes this launcher work in a shell that never sourced riabuild's
  # environment — `ssh box bin/codex-3`, a cron entry, an editor that sanitised
  # its environment. Without it those all fail with "env: 'node': No such file
  # or directory", on a machine where Codex is installed perfectly well.
  #
  # Only on this branch. The fallback above has no recorded binary, so there is
  # no directory to derive a Node from, and whatever PATH offers is all it ever
  # had.
  codex_node_bin="${{codex_binary%/*}}"
  if [ -n "$codex_node_bin" ]; then
    PATH="$codex_node_bin:$PATH"
    export PATH
  fi
fi
# --yolo is a default, not an imposition, and it has to be: Codex refuses the
# flag twice ("cannot be used multiple times") and refuses it beside
# --ask-for-approval ("cannot be used with"). Appending it unconditionally would
# make `codex --yolo` and `codex -a on-request` — the two things a developer who
# knows this tool is most likely to type — fail in the parser, naming a flag
# they never typed. So it is added only where the developer expressed no
# approval policy of their own.
for riabuild_arg do
  case "$riabuild_arg" in
    --yolo | {yolo_long} | -a | -a* | --ask-for-approval | --ask-for-approval=*)
      exec "$codex_binary" "$@"
      ;;
  esac
done
exec "$codex_binary" --yolo "$@"
"#,
        codex_home = codex_home.display(),
        bin_dir = bin_dir.display(),
        yolo_long = YOLO_LONG,
    )
}

/// Writes `codex` and `codex-1` … `codex-9`.
///
/// `codex` and `codex-1` are the same script, which is what makes the bare name
/// mean profile 1 — the shape `shims::write_all` already uses for `claude` and
/// `claude-1`.
///
/// Each is landed by rename and then made executable, like every other
/// generated script: the hazard is an interrupt mid-write leaving a truncated
/// launcher that fails with a shell syntax error.
pub async fn write(ctx: &crate::Ctx) -> Result<()> {
    let bin = ctx.paths.bin_dir();
    tokio::fs::create_dir_all(&bin).await?;
    let codex = ctx.codex();

    for profile in 1..=PROFILES {
        let script = launcher_script(&ctx.paths.codex_profile_dir(profile), &codex, &bin);
        write_launcher(&bin.join(format!("codex-{profile}")), &script).await?;
        if profile == 1 {
            write_launcher(&bin.join("codex"), &script).await?;
        }
    }
    Ok(())
}

/// Every launcher this module owns, in the order `check()` reports them.
///
/// One list, so a `check()` that verifies the set and an `apply()` that writes
/// it cannot come to disagree about what the set is.
pub fn launcher_names() -> Vec<String> {
    let mut names = vec!["codex".to_string()];
    names.extend((1..=PROFILES).map(|profile| format!("codex-{profile}")));
    names
}

/// Which profile a launcher opens: `codex` and `codex-1` both open profile 1.
pub fn profile_of(name: &str) -> usize {
    name.strip_prefix("codex-")
        .and_then(|number| number.parse().ok())
        .unwrap_or(1)
}

async fn write_launcher(path: &Path, script: &str) -> Result<()> {
    riabuild_paths::config::write_atomic(path, script.as_bytes()).await?;
    make_executable(path).await?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::testing::ctx_with;
    use riabuild_runner::FakeRunner;

    fn script() -> String {
        launcher_script(
            Path::new("/home/ada/.riabuild/codex"),
            "/home/ada/.riabuild/node/24.19.0/bin/codex",
            Path::new("/home/ada/.riabuild/bin"),
        )
    }

    #[test]
    fn the_launcher_pins_the_config_directory_riabuild_owns() {
        let script = script();
        assert!(
            script.contains(r#"CODEX_HOME="/home/ada/.riabuild/codex""#),
            "{script}"
        );
        assert!(script.contains("export CODEX_HOME"), "{script}");
    }

    #[test]
    fn the_launcher_creates_a_config_directory_that_is_not_there() {
        // Codex hard-fails on a missing CODEX_HOME rather than creating one, so
        // a launcher that only named it would break the moment a developer
        // cleaned up — and stay broken until the next `riabuild`.
        let script = script();
        assert!(
            script.contains(r#"[ -d "$CODEX_HOME" ] || mkdir -p "$CODEX_HOME""#),
            "{script}"
        );
    }

    #[test]
    fn the_launcher_adds_yolo_by_default() {
        let script = script();
        assert!(
            script.contains(r#"exec "$codex_binary" --yolo "$@""#),
            "{script}"
        );
    }

    #[test]
    fn the_launcher_stands_aside_for_an_approval_policy_the_developer_chose() {
        // Codex refuses --yolo twice and refuses it beside --ask-for-approval,
        // so appending it unconditionally turns `codex --yolo` and
        // `codex -a on-request` into parser errors naming a flag the developer
        // never typed.
        let script = script();
        for spelling in [
            "--yolo",
            YOLO_LONG,
            "-a",
            "-a*",
            "--ask-for-approval",
            "--ask-for-approval=*",
        ] {
            assert!(
                script.contains(spelling),
                "{spelling} is not matched: {script}"
            );
        }
        assert!(script.contains(r#"exec "$codex_binary" "$@""#), "{script}");
    }

    #[test]
    fn the_launcher_can_never_exec_itself() {
        // `bin/` leads PATH inside the environment shell, so a bare `codex`
        // would resolve straight back to this script. The strip is what stops
        // the fallback becoming an exec loop.
        let script = script();
        assert!(
            script.contains(r#"grep -vxF "/home/ada/.riabuild/bin""#),
            "{script}"
        );
    }

    #[test]
    fn a_codex_with_no_pinned_node_is_treated_as_no_path_at_all() {
        // The bare name is what `Ctx::codex()` falls back to before a Node is
        // pinned, and `-x codex` would then be satisfied by a file of that name
        // in whatever directory the developer is standing in.
        let script = launcher_script(
            Path::new("/home/ada/.riabuild/codex"),
            "codex",
            Path::new("/home/ada/.riabuild/bin"),
        );
        assert!(script.contains(r#"*) codex_binary="" ;;"#), "{script}");
    }

    #[test]
    fn the_launcher_carries_riabuilds_own_node() {
        // Codex is a Node script — npm installs bin/codex as a symlink to a
        // codex.js whose shebang is `#!/usr/bin/env node` — so a launcher that
        // named only the binary works exactly on the machines that happen to
        // have a Node of their own.
        let script = script();
        assert!(
            script.contains(r#"PATH="$codex_node_bin:$PATH""#),
            "{script}"
        );
        assert!(
            script.contains(r#"codex_node_bin="${codex_binary%/*}""#),
            "the launcher does not derive the Node directory from the binary: {script}"
        );
    }

    /// The launcher starting Codex on a machine whose `PATH` carries no Node.
    ///
    /// The text assertions above cannot see this: `PATH="$codex_node_bin:$PATH"`
    /// is present in a script that exports it too late, on the wrong branch, or
    /// with a `codex_node_bin` that expanded to nothing, and every one of those
    /// reads the same. So this runs the generated script and asks what `PATH`
    /// it actually handed the binary.
    ///
    /// A stand-in `codex` that prints its `PATH` rather than a real one, which
    /// is what keeps this out of the `#[ignore]`d pair above: the question here
    /// is what the *launcher* exports, and a real Codex would answer it no
    /// better while making the test need an install.
    #[tokio::test]
    #[cfg(unix)]
    async fn the_launcher_starts_codex_where_the_machine_has_no_node() {
        use riabuild_runner::{CommandRunner, RealRunner, RunOptions};

        let home = tempfile::TempDir::new().unwrap();
        let node_bin = home.path().join("node").join("24.19.0").join("bin");
        let bin = home.path().join("bin");
        tokio::fs::create_dir_all(&node_bin).await.unwrap();
        tokio::fs::create_dir_all(&bin).await.unwrap();

        // Where npm puts it: beside the Node that interprets it.
        let codex = node_bin.join("codex");
        tokio::fs::write(&codex, "#!/bin/sh\nprintf '%s' \"$PATH\"\n")
            .await
            .unwrap();
        make_executable(&codex).await.unwrap();

        let launcher = bin.join("codex");
        let script = launcher_script(
            &home.path().join("codex-home"),
            &codex.to_string_lossy(),
            &bin,
        );
        tokio::fs::write(&launcher, script.as_bytes())
            .await
            .unwrap();
        make_executable(&launcher).await.unwrap();

        // The server shape: riabuild under a non-interactive SSH exec, whose
        // PATH is this and which carries no Node anywhere.
        let output = RealRunner
            .run(
                &launcher.to_string_lossy(),
                &[],
                &RunOptions {
                    env: vec![(
                        "PATH".to_string(),
                        "/usr/local/bin:/usr/bin:/bin".to_string(),
                    )],
                    ..Default::default()
                },
            )
            .await
            .expect("the launcher runs");

        assert!(output.ok(), "{output:?}");
        assert!(
            output
                .stdout
                .starts_with(&node_bin.to_string_lossy().into_owned()),
            "the launcher did not lead PATH with riabuild's own Node: {:?}",
            output.stdout
        );
    }

    #[test]
    fn the_launcher_set_is_the_bare_name_and_nine_numbers() {
        let names = launcher_names();
        assert_eq!(names.len(), PROFILES + 1);
        assert_eq!(names[0], "codex");
        assert_eq!(names[1], "codex-1");
        assert_eq!(names[PROFILES], "codex-9");
    }

    #[test]
    fn the_bare_name_and_the_first_number_are_one_profile() {
        assert_eq!(profile_of("codex"), 1);
        assert_eq!(profile_of("codex-1"), 1);
        assert_eq!(profile_of("codex-9"), 9);
    }

    #[tokio::test]
    async fn writing_lays_down_every_launcher() {
        let (ctx, _home) = ctx_with(FakeRunner::new()).await;
        write(&ctx).await.expect("the launchers are written");

        for name in launcher_names() {
            let path = ctx.paths.bin_dir().join(&name);
            assert!(is_executable(&path).await, "{name} is not executable");
        }
    }

    #[tokio::test]
    async fn the_launcher_is_written_executable() {
        let (ctx, _home) = ctx_with(FakeRunner::new()).await;
        write(&ctx).await.expect("the launcher is written");

        let path = ctx.paths.bin_dir().join("codex");
        let script = tokio::fs::read_to_string(&path)
            .await
            .expect("read it back");
        assert!(
            script.contains(&ctx.paths.codex_dir().to_string_lossy().into_owned()),
            "{script}"
        );
        assert!(is_executable(&path).await, "{}", path.display());
    }

    /// Runs the generated launcher against a real Codex.
    ///
    /// Everything above asserts the *text* of a shell script, which is as far
    /// as a unit test can go and is not the same as the script working. The
    /// three facts this launcher is built on — `--yolo` accepted ahead of a
    /// subcommand, Codex refusing a `CODEX_HOME` that does not exist, and Codex
    /// rejecting `--yolo` beside `--ask-for-approval` or twice — are all
    /// undocumented, so an upstream change should surface as a test failure
    /// rather than as broken laptops. `#[ignore]`d because it needs a real
    /// install: run `cargo test -- --ignored` when `MIN_VERSION` moves.
    #[tokio::test]
    #[ignore = "needs a real Codex CLI install; pins the undocumented behaviour the launcher is built on"]
    async fn the_generated_launcher_runs_a_real_codex() {
        use riabuild_runner::{CommandRunner, RealRunner, RunOptions};
        let runner = RealRunner;
        let Some(codex) = runner.which("codex") else {
            panic!("codex is not installed; this test needs it");
        };

        let home = tempfile::TempDir::new().unwrap();
        let bin = home.path().join("bin");
        // Deliberately not created: the launcher creating it is the behaviour
        // under test, and a Codex pointed at a missing one refuses to start.
        let codex_home = home.path().join("codex");
        tokio::fs::create_dir_all(&bin).await.unwrap();

        let launcher = bin.join("codex");
        let script = launcher_script(&codex_home, &codex.to_string_lossy(), &bin);
        tokio::fs::write(&launcher, script.as_bytes())
            .await
            .unwrap();
        make_executable(&launcher).await.unwrap();

        let path = launcher.to_string_lossy().into_owned();
        let version = runner
            .run(&path, &["--version"], &RunOptions::default())
            .await
            .expect("the launcher runs");
        assert!(version.ok(), "{version:?}");
        assert!(version.stdout.contains("codex-cli"), "{version:?}");
        assert!(
            tokio::fs::try_exists(&codex_home).await.unwrap(),
            "the launcher creates the CODEX_HOME Codex refuses to start without"
        );

        // The two invocations an unconditional `--yolo` would break, each
        // failing in Codex's parser and naming a flag the developer never
        // typed.
        for args in [
            vec!["--yolo", "--version"],
            vec!["-a", "on-request", "--version"],
        ] {
            let output = runner
                .run(&path, &args, &RunOptions::default())
                .await
                .expect("the launcher runs");
            assert!(output.ok(), "{args:?} was rejected: {output:?}");
        }
    }

    /// Two launchers, two accounts, against a real Codex.
    ///
    /// This is the claim the other eight launchers exist for, and the one that
    /// cannot be made by reading a generated script: that pointing Codex at two
    /// `CODEX_HOME`s really does keep two sign-ins apart, rather than both
    /// landing in one store the way a keychain-backed tool would. Nine scripts
    /// that each export a different directory and yet share an account would
    /// pass every other test in this file.
    ///
    /// Uses `login --with-api-key`, which reads the key from stdin, so it needs
    /// no browser and no real credential — Codex records whatever it is given
    /// and reports it back, which is all this asserts.
    ///
    /// `#[ignore]`d because it needs a real install: run
    /// `cargo test -- --ignored` when `MIN_VERSION` moves.
    #[tokio::test]
    #[ignore = "needs a real Codex CLI install; pins that CODEX_HOME really does separate sign-ins"]
    async fn two_launchers_hold_two_independent_logins() {
        use riabuild_runner::{CommandRunner, RealRunner, RunOptions};
        let runner = RealRunner;
        let Some(codex) = runner.which("codex") else {
            panic!("codex is not installed; this test needs it");
        };

        let home = tempfile::TempDir::new().unwrap();
        let bin = home.path().join("bin");
        tokio::fs::create_dir_all(&bin).await.unwrap();

        let mut launchers = Vec::new();
        for profile in [1usize, 2] {
            let codex_home = home.path().join("codex").join(profile.to_string());
            let script = launcher_script(&codex_home, &codex.to_string_lossy(), &bin);
            let path = bin.join(format!("codex-{profile}"));
            tokio::fs::write(&path, script.as_bytes()).await.unwrap();
            make_executable(&path).await.unwrap();
            launchers.push(path.to_string_lossy().into_owned());
        }

        let sign_in = |launcher: String, key: &'static str| {
            let runner = RealRunner;
            async move {
                runner
                    .run(
                        &launcher,
                        &["login", "--with-api-key"],
                        &RunOptions {
                            stdin: Some(format!("{key}\n").into_bytes()),
                            ..Default::default()
                        },
                    )
                    .await
                    .expect("the launcher runs")
            }
        };
        // `codex login status` reports on **stderr**, not stdout — verified
        // against 0.147.0. Reading `.stdout` here gets an empty string and an
        // assertion that fails for the wrong reason, so both streams are joined
        // rather than one being guessed at.
        let status = |launcher: String| {
            let runner = RealRunner;
            async move {
                let out = runner
                    .run(&launcher, &["login", "status"], &RunOptions::default())
                    .await
                    .expect("the launcher runs");
                format!("{}{}", out.stdout, out.stderr)
            }
        };

        let first = sign_in(launchers[0].clone(), "sk-test-AAAA1111").await;
        assert!(first.ok(), "signing in to codex-1: {first:?}");
        let second = sign_in(launchers[1].clone(), "sk-test-BBBB2222").await;
        assert!(second.ok(), "signing in to codex-2: {second:?}");

        // Both at once. If the two shared a store, whichever signed in last
        // would be the only account either launcher could see.
        let one = status(launchers[0].clone()).await;
        let two = status(launchers[1].clone()).await;
        assert!(one.contains("A1111"), "codex-1 lost its own account: {one}");
        assert!(two.contains("B2222"), "codex-2 lost its own account: {two}");

        // And leaving one does not leave the other.
        let out = RealRunner
            .run(&launchers[1], &["logout"], &RunOptions::default())
            .await
            .expect("the launcher runs");
        assert!(out.ok(), "{out:?}");
        let one = status(launchers[0].clone()).await;
        let two = status(launchers[1].clone()).await;
        assert!(
            one.contains("A1111"),
            "codex-2's logout took codex-1: {one}"
        );
        assert!(
            !two.contains("B2222"),
            "codex-2 is still signed in after logout: {two}"
        );
    }

    #[cfg(unix)]
    async fn is_executable(path: &Path) -> bool {
        use std::os::unix::fs::PermissionsExt;
        tokio::fs::metadata(path)
            .await
            .map(|meta| meta.permissions().mode() & 0o111 != 0)
            .unwrap_or(false)
    }

    #[cfg(not(unix))]
    async fn is_executable(path: &Path) -> bool {
        tokio::fs::try_exists(path).await.unwrap_or(false)
    }
}
