//! `~/.riabuild/bin/codex` — the Codex CLI launcher.
//!
//! The same shape as the Claude Code launcher next door, for the same reasons:
//! a small generated script in `bin/` that pins the config directory riabuild
//! owns, adds the flags the team wants by default, and falls back to `PATH`
//! when the binary it recorded has moved.
//!
//! ```sh
//! CODEX_HOME=~/.riabuild/codex codex --yolo
//! ```
//!
//! There is one launcher rather than nine. Claude Code's numbering exists to
//! keep several *sign-ins* apart, and riabuild does not sign anyone in to Codex
//! — so a second directory would hold nothing that distinguishes it from the
//! first, and `riabuild claude delete 3` would grow a counterpart with no
//! account to delete.
//!
//! Three things the Claude launcher does are deliberately **not** copied here.
//! `unset SSH_CONNECTION SSH_CLIENT SSH_TTY` and the `WAYLAND_DISPLAY` claim
//! are workarounds for behaviour read out of the Claude Code binary, and the
//! `--settings` layer carries the org's Claude settings; none of the three is a
//! fact about Codex. Asserting them here would be inventing an upstream
//! behaviour rather than accommodating one.

use anyhow::Result;
use riabuild_fetch::archive::make_executable;
use std::path::Path;

/// What `--yolo` is short for, and what the launcher has to look for in the
/// developer's own arguments before adding it.
///
/// Codex rejects the flag twice — "cannot be used multiple times" — so a
/// launcher that always appended it would turn a developer typing the obvious
/// `codex --yolo` into a parser error naming a flag they did not type.
const YOLO_LONG: &str = "--dangerously-bypass-approvals-and-sandbox";

/// The launcher, which is the only thing that names `CODEX_HOME`.
///
/// Not exported into the environment shell, for the reason `CLAUDE_CONFIG_DIR`
/// is not: an exported value follows every `codex` a developer starts by any
/// route, including one they deliberately ran from outside riabuild's tree.
pub fn launcher_script(codex_home: &Path, codex: &str, bin_dir: &Path) -> String {
    format!(
        r#"#!/bin/sh
# Generated by riabuild. Edits here are overwritten.
#
# Launches the Codex CLI against the config directory riabuild owns, with
# approvals and the sandbox bypassed by default.
set -e
CODEX_HOME="{codex_home}"
export CODEX_HOME
# Codex refuses to start against a CODEX_HOME that is not there — "Error finding
# codex home" — rather than creating one, so naming the directory is only half
# of pointing at it. Created here as well as by the `codex_cli` task because the
# gap between two riabuild runs is exactly where a `rm -rf` lands: the task
# would go on reporting a satisfied machine, and every `codex` until the next
# run would refuse to start.
[ -d "$CODEX_HOME" ] || mkdir -p "$CODEX_HOME"
codex_binary="{codex}"
case "$codex_binary" in
  /*) ;;
  # A non-absolute path (no Node pinned yet) can't be trusted with the -x test
  # below: a same-named executable in the current directory would pass it, skip
  # the PATH strip, and exec a bare name that PATH search resolves straight back
  # to this script.
  *) codex_binary="" ;;
esac
if [ ! -x "$codex_binary" ]; then
  # The recorded binary is gone: a `codex update`, or a Node version change
  # since the last run. Fall back to PATH with riabuild's own bin/ removed —
  # without that this script finds itself, because bin/ comes first inside the
  # environment shell.
  PATH=$(printf '%s' "$PATH" | tr ':' '\n' | grep -vxF "{bin_dir}" | paste -sd: -)
  export PATH
  codex_binary=codex
fi
# --yolo is a default, not an imposition, and it has to be: Codex refuses the
# flag twice ("cannot be used multiple times") and refuses it beside
# --ask-for-approval ("cannot be used with"). Appending it unconditionally would
# make `codex --yolo` and `codex -a on-request` — the two things a developer who
# knows this tool is most likely to type — fail in the parser, naming a flag
# they never typed. So it is added only where the developer expressed no
# approval policy of their own.
for riabuild_arg do
  case "$riabuild_arg" in
    --yolo | {yolo_long} | -a | -a* | --ask-for-approval | --ask-for-approval=*)
      exec "$codex_binary" "$@"
      ;;
  esac
done
exec "$codex_binary" --yolo "$@"
"#,
        codex_home = codex_home.display(),
        bin_dir = bin_dir.display(),
        yolo_long = YOLO_LONG,
    )
}

/// Writes `~/.riabuild/bin/codex`.
///
/// Landed by rename and then made executable, like every other generated
/// script: the hazard is an interrupt mid-write leaving a truncated launcher
/// that fails with a shell syntax error.
pub async fn write(ctx: &crate::Ctx) -> Result<()> {
    let bin = ctx.paths.bin_dir();
    tokio::fs::create_dir_all(&bin).await?;

    let script = launcher_script(&ctx.paths.codex_dir(), &ctx.codex(), &bin);
    let path = bin.join("codex");
    riabuild_paths::config::write_atomic(&path, script.as_bytes()).await?;
    make_executable(&path).await?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::testing::ctx_with;
    use riabuild_runner::FakeRunner;

    fn script() -> String {
        launcher_script(
            Path::new("/home/ada/.riabuild/codex"),
            "/home/ada/.riabuild/node/24.19.0/bin/codex",
            Path::new("/home/ada/.riabuild/bin"),
        )
    }

    #[test]
    fn the_launcher_pins_the_config_directory_riabuild_owns() {
        let script = script();
        assert!(
            script.contains(r#"CODEX_HOME="/home/ada/.riabuild/codex""#),
            "{script}"
        );
        assert!(script.contains("export CODEX_HOME"), "{script}");
    }

    #[test]
    fn the_launcher_creates_a_config_directory_that_is_not_there() {
        // Codex hard-fails on a missing CODEX_HOME rather than creating one, so
        // a launcher that only named it would break the moment a developer
        // cleaned up — and stay broken until the next `riabuild`.
        let script = script();
        assert!(
            script.contains(r#"[ -d "$CODEX_HOME" ] || mkdir -p "$CODEX_HOME""#),
            "{script}"
        );
    }

    #[test]
    fn the_launcher_adds_yolo_by_default() {
        let script = script();
        assert!(
            script.contains(r#"exec "$codex_binary" --yolo "$@""#),
            "{script}"
        );
    }

    #[test]
    fn the_launcher_stands_aside_for_an_approval_policy_the_developer_chose() {
        // Codex refuses --yolo twice and refuses it beside --ask-for-approval,
        // so appending it unconditionally turns `codex --yolo` and
        // `codex -a on-request` into parser errors naming a flag the developer
        // never typed.
        let script = script();
        for spelling in [
            "--yolo",
            YOLO_LONG,
            "-a",
            "-a*",
            "--ask-for-approval",
            "--ask-for-approval=*",
        ] {
            assert!(
                script.contains(spelling),
                "{spelling} is not matched: {script}"
            );
        }
        assert!(script.contains(r#"exec "$codex_binary" "$@""#), "{script}");
    }

    #[test]
    fn the_launcher_can_never_exec_itself() {
        // `bin/` leads PATH inside the environment shell, so a bare `codex`
        // would resolve straight back to this script. The strip is what stops
        // the fallback becoming an exec loop.
        let script = script();
        assert!(
            script.contains(r#"grep -vxF "/home/ada/.riabuild/bin""#),
            "{script}"
        );
    }

    #[test]
    fn a_codex_with_no_pinned_node_is_treated_as_no_path_at_all() {
        // The bare name is what `Ctx::codex()` falls back to before a Node is
        // pinned, and `-x codex` would then be satisfied by a file of that name
        // in whatever directory the developer is standing in.
        let script = launcher_script(
            Path::new("/home/ada/.riabuild/codex"),
            "codex",
            Path::new("/home/ada/.riabuild/bin"),
        );
        assert!(script.contains(r#"*) codex_binary="" ;;"#), "{script}");
    }

    #[tokio::test]
    async fn the_launcher_is_written_executable() {
        let (ctx, _home) = ctx_with(FakeRunner::new()).await;
        write(&ctx).await.expect("the launcher is written");

        let path = ctx.paths.bin_dir().join("codex");
        let script = tokio::fs::read_to_string(&path)
            .await
            .expect("read it back");
        assert!(
            script.contains(&ctx.paths.codex_dir().to_string_lossy().into_owned()),
            "{script}"
        );
        assert!(is_executable(&path).await, "{}", path.display());
    }

    /// Runs the generated launcher against a real Codex.
    ///
    /// Everything above asserts the *text* of a shell script, which is as far
    /// as a unit test can go and is not the same as the script working. The
    /// three facts this launcher is built on — `--yolo` accepted ahead of a
    /// subcommand, Codex refusing a `CODEX_HOME` that does not exist, and Codex
    /// rejecting `--yolo` beside `--ask-for-approval` or twice — are all
    /// undocumented, so an upstream change should surface as a test failure
    /// rather than as broken laptops. `#[ignore]`d because it needs a real
    /// install: run `cargo test -- --ignored` when `MIN_VERSION` moves.
    #[tokio::test]
    #[ignore = "needs a real Codex CLI install; pins the undocumented behaviour the launcher is built on"]
    async fn the_generated_launcher_runs_a_real_codex() {
        use riabuild_runner::{CommandRunner, RealRunner, RunOptions};
        let runner = RealRunner;
        let Some(codex) = runner.which("codex") else {
            panic!("codex is not installed; this test needs it");
        };

        let home = tempfile::TempDir::new().unwrap();
        let bin = home.path().join("bin");
        // Deliberately not created: the launcher creating it is the behaviour
        // under test, and a Codex pointed at a missing one refuses to start.
        let codex_home = home.path().join("codex");
        tokio::fs::create_dir_all(&bin).await.unwrap();

        let launcher = bin.join("codex");
        let script = launcher_script(&codex_home, &codex.to_string_lossy(), &bin);
        tokio::fs::write(&launcher, script.as_bytes())
            .await
            .unwrap();
        make_executable(&launcher).await.unwrap();

        let path = launcher.to_string_lossy().into_owned();
        let version = runner
            .run(&path, &["--version"], &RunOptions::default())
            .await
            .expect("the launcher runs");
        assert!(version.ok(), "{version:?}");
        assert!(version.stdout.contains("codex-cli"), "{version:?}");
        assert!(
            tokio::fs::try_exists(&codex_home).await.unwrap(),
            "the launcher creates the CODEX_HOME Codex refuses to start without"
        );

        // The two invocations an unconditional `--yolo` would break, each
        // failing in Codex's parser and naming a flag the developer never
        // typed.
        for args in [
            vec!["--yolo", "--version"],
            vec!["-a", "on-request", "--version"],
        ] {
            let output = runner
                .run(&path, &args, &RunOptions::default())
                .await
                .expect("the launcher runs");
            assert!(output.ok(), "{args:?} was rejected: {output:?}");
        }
    }

    #[cfg(unix)]
    async fn is_executable(path: &Path) -> bool {
        use std::os::unix::fs::PermissionsExt;
        tokio::fs::metadata(path)
            .await
            .map(|meta| meta.permissions().mode() & 0o111 != 0)
            .unwrap_or(false)
    }

    #[cfg(not(unix))]
    async fn is_executable(path: &Path) -> bool {
        tokio::fs::try_exists(path).await.unwrap_or(false)
    }
}
