//! `~/.riabuild/bin` — the small scripts that make the environment work.
//!
//! The important ones are the Claude Code launchers: `claude` runs the primary
//! account, and `claude-1` … `claude-N` each run their own. Every one launches
//! Claude Code with that account's config directory and the org settings
//! layered over it.
//!
//! What each of them *does* lives in `claude`, beside the `codex` and `grok`
//! launchers, and is Rust: `launch` is the command they all `exec`, and the
//! reason none of them is a shell script any more. What this module owns is the
//! machinery underneath all of them — putting one generated script in `bin/`,
//! executable and landed by rename — and the shims for the tools riabuild
//! shadows there: the clipboard three, `xdg-open`, and the two that carry a
//! credential to the tool they start, `ngrok` and `infisical`.
//!
//! **Every generated script in here is one `exec` line.** That is a deliberate
//! ceiling rather than a coincidence of what they happen to need: a shell
//! script has no type checker, no test that runs without a subprocess, and a
//! parser that turns a mistake into a different working program instead of into
//! an error. A branch, a substitution or a pipeline appearing in one of these
//! files means logic has leaked back out of Rust, and
//! `every_generated_script_is_a_single_exec` fails when it does.
//!
//! Every shim here names the riabuild binary by **absolute path**, and none of
//! them may go back to a bare `riabuild`. riabuild does not put its own binary
//! on `PATH`: it lives at `<tools>/riabuild/<version>/riabuild`, while
//! `shell::riabuild_path_dirs` leads `PATH` with `bin/` and Node's `bin/` and
//! nothing else. A bare name therefore resolves to whatever *else* is called
//! riabuild on that machine — on a server with an apt or Homebrew copy, some
//! other version; on a server without one, nothing at all, and `$BROWSER`
//! becomes `xdg-open: exec: riabuild: not found`.

pub mod browser;
pub mod claude;
pub mod clipboard;
pub mod codex;
pub mod grok;
pub mod launch;

pub use claude::{launcher_script, write_all};
pub use launch::{Harness, Plan};

use crate::Ctx;
use crate::shell::shell_quote;
use anyhow::{Context, Result};
use riabuild_fetch::archive::make_executable;
use std::path::Path;

/// `~/.riabuild/bin/<name>`, handing off to a binary in its own versioned tree.
///
/// Used for pnpm and `gh` alike. pnpm is the one that *requires* it: pnpm 11
/// loads `dist/` from beside its executable, so copying the executable onto
/// `PATH` by itself gets `Cannot find module .../dist/pnpm.mjs`. A symlink also
/// works today, because Node resolves `process.execPath` through symlinks, but
/// that is an implementation detail of the runtime pnpm happens to be built on.
///
/// `gh` is a single static binary that could be copied, and uses a shim anyway
/// so that `bin/` is uniformly a directory of small scripts and a version bump
/// rewrites one line instead of moving 30 MB.
pub fn exec_shim(binary: &Path) -> String {
    format!(
        r#"#!/bin/sh
# Generated by riabuild. Edits here are overwritten.
exec {binary} "$@"
"#,
        binary = shell_quote(&binary.to_string_lossy()),
    )
}

/// `~/.riabuild/bin/<name>`, handing off to a **script** through the Node
/// riabuild owns.
///
/// pnpm is the one that needs this, and needs it on every platform: there is no
/// pnpm executable that runs on a bare Linux. `@pnpm/linux-x64` is linked
/// against `libatomic.so.1`, which arrives with a toolchain and is therefore
/// absent from exactly the machines a provisioner is pointed at, and
/// `@pnpm/linuxstatic-x64` is musl and asks for a loader that is not there
/// either — so riabuild installs pnpm's JavaScript and hands it to the Node it
/// downloaded and verified itself. `download::PNPM_PACKAGE` carries the
/// evidence.
///
/// Both paths are absolute, for the reason in the module header and for the one
/// in `../../../CLAUDE.md`'s Codex section: during provisioning nothing riabuild
/// owns is on `PATH`, so a `#!/usr/bin/env node` shebang finds whatever Node the
/// machine has — on a server reached by a non-interactive SSH exec, whose `PATH`
/// is `/usr/local/bin:/usr/bin:/bin`, that is nothing at all, and the 127 it
/// exits with reads to `check()` as "pnpm is not installed".
pub fn node_shim(node: &Path, script: &Path) -> String {
    format!(
        r#"#!/bin/sh
# Generated by riabuild. Edits here are overwritten.
exec {node} {script} "$@"
"#,
        node = shell_quote(&node.to_string_lossy()),
        script = shell_quote(&script.to_string_lossy()),
    )
}

/// Writes `~/.riabuild/bin/<name>` for one owned tool.
///
/// This is what puts the owned copy in front of any system one for the
/// developer's own commands: `~/.riabuild/bin` is first on `PATH` inside the
/// environment shell. riabuild's own calls do not rely on it — they run the
/// versioned path directly, because during provisioning that `PATH` does not
/// exist yet.
pub async fn write_tool(ctx: &Ctx, name: &str, binary: &Path) -> Result<()> {
    write_script(&ctx.paths.bin_dir(), name, &exec_shim(binary)).await
}

/// Puts one generated script in `bin/`, executable and landed by rename.
///
/// **Every** shim and launcher this crate writes goes through here — the tool
/// shims, the clipboard three, `xdg-open`, `ngrok`, and the `claude`, `codex`
/// and `grok` launchers. There were seven copies of these same three calls, two
/// of them (`codex::write_launcher` and `grok::write_launcher`) byte-identical
/// to a third in this module, and the drift they invite is not cosmetic: a copy
/// that forgets `make_executable` writes a perfectly good script the developer
/// gets `permission denied` from, and a copy that reaches for
/// `tokio::fs::write` leaves whichever colleague is mid-`exec` a truncated
/// shell script. Both are one line missing from one of seven places, and
/// neither fails to compile.
///
/// `create_dir_all` here rather than at each caller for the same reason: a
/// launcher written into a `bin/` nobody made is `NotFound`, and it is a
/// no-op every time after the first.
pub(crate) async fn write_script(bin: &Path, name: &str, script: &str) -> Result<()> {
    tokio::fs::create_dir_all(bin).await?;
    let path = bin.join(name);
    riabuild_paths::config::write_atomic(&path, script.as_bytes()).await?;
    make_executable(&path).await?;
    Ok(())
}

/// The tools riabuild shadows in `~/.riabuild/bin`.
///
/// One per direction per session type: xclip does both on X11, and Wayland
/// splits them across wl-paste and wl-copy. Every name here must also be a
/// `Tool` the shim can parse — one without a parser would shadow a working
/// binary with one that passes everything through.
pub const CLIPBOARD_TOOLS: &[&str] = &["xclip", "wl-paste", "wl-copy"];

/// `~/.riabuild/bin/xclip`, `wl-paste` and `wl-copy`.
///
/// All three route into riabuild, which decides whether the invocation is a
/// clipboard transfer to send down the channel or something to hand to the real
/// binary. They are written on the *server*, where `~/.riabuild/bin` leads
/// `PATH` and Claude Code's probe finds them first.
///
/// Written by `provision::write_launchers`, under the same condition
/// `shell::browser_for` uses to export `BROWSER` — see the note there for why
/// the two must not drift apart.
///
/// `riabuild` is the absolute path of the binary writing them; see the module
/// header for why it can never be the bare name.
pub async fn write_clipboard_shims(ctx: &Ctx, riabuild: &Path) -> Result<()> {
    let bin = ctx.paths.bin_dir();
    // One per direction per session type: xclip does both on X11, and Wayland
    // splits them across wl-paste and wl-copy.
    for tool in CLIPBOARD_TOOLS {
        write_script(&bin, tool, &clipboard_shim_script(riabuild, tool)).await?;
    }
    Ok(())
}

/// `~/.riabuild/bin/<tool>` for one clipboard tool.
pub fn clipboard_shim_script(riabuild: &Path, tool: &str) -> String {
    format!(
        r#"#!/bin/sh
# Generated by riabuild. Edits here are overwritten.
#
# Carries the clipboard between this server and the laptop over the riabuild
# channel. Anything that is not a clipboard transfer is handed to the real
# {tool} on PATH.
#
# riabuild is named in full because it is not on PATH: it lives in its own
# versioned directory, and a bare name would find another machine's copy or
# none at all.
exec {riabuild} channel shim {tool} "$@"
"#,
        riabuild = shell_quote(&riabuild.to_string_lossy()),
    )
}

/// `~/.riabuild/bin/ngrok` — ngrok, with the team's authtoken in its
/// environment and nowhere else.
///
/// The token is the org's, it is long-lived, and riabuild does not write this
/// class of secret down: not into ngrok's own `ngrok.yml`, not into a generated
/// rcfile, not into this script. It is fetched on **every** invocation, so a
/// token a lead rotates this morning is in effect this morning, and the audit
/// row the fetch writes says somebody used the team's tunnel credential rather
/// than that somebody opened a terminal.
///
/// The token reaches ngrok in its environment and never in an argument — `ps`
/// is world-readable, and on a shared server it shows one developer's command
/// lines to all the others — and it is not in this file either, which is on
/// disk.
///
/// **This shim used to hold the one piece of shell in `bin/` that handled a
/// secret**, and it was the sharpest argument for moving all of them into Rust.
/// It read
///
/// ```sh
/// NGROK_AUTHTOKEN=$("…/riabuild" internal ngrok-token)
/// if [ -n "$NGROK_AUTHTOKEN" ]; then export NGROK_AUTHTOKEN; else unset NGROK_AUTHTOKEN; fi
/// ```
///
/// — a command substitution whose *stdout was a credential*, which made "print
/// nothing else on stdout" a rule the whole of `internal ngrok-token` had to
/// keep, and which put a token in a shell variable in a process that then went
/// on to `exec`. `riabuild internal ngrok` fetches it in the process that is
/// about to become ngrok and passes it in that process's own environment, so it
/// is never a variable in a shell, never a line on a pipe, and never anything
/// `set -x` could print.
///
/// A fetch that fails prints riabuild's own explanation on stderr and starts
/// ngrok with the variable **absent** rather than empty: an empty
/// `NGROK_AUTHTOKEN` reads to ngrok as *not authenticated* and would override a
/// token a developer had configured for themselves. ngrok still runs, because
/// `ngrok --version` and `ngrok help` should work on a plane.
///
/// `riabuild` is named in full for the reason in the module header, and so is
/// ngrok: this shim *is* what `PATH` finds, so a bare `ngrok` here would find
/// this script.
pub fn ngrok_shim_script(riabuild: &Path, ngrok: &Path) -> String {
    format!(
        r#"#!/bin/sh
# Generated by riabuild. Edits here are overwritten.
#
# Runs ngrok with the team's authtoken, fetched from riabuild-web on every
# invocation and stored nowhere on this machine. The token reaches ngrok in its
# environment and never in an argument, because `ps` shows argument lists to
# every account on the machine — and never through this file, which does no
# more than name the two binaries involved.
#
# A fetch that fails says so on stderr and leaves ngrok unauthenticated rather
# than refusing to start.
exec {riabuild} internal ngrok --binary {ngrok} -- "$@"
"#,
        riabuild = shell_quote(&riabuild.to_string_lossy()),
        ngrok = shell_quote(&ngrok.to_string_lossy()),
    )
}

/// Writes `~/.riabuild/bin/ngrok`.
///
/// Deliberately not `write_tool`: every other owned tool is handed straight to
/// `exec`, and this one has to carry a credential to the process it starts.
pub async fn write_ngrok_shim(ctx: &Ctx, riabuild: &Path, ngrok: &Path) -> Result<()> {
    let bin = ctx.paths.bin_dir();
    write_script(&bin, "ngrok", &ngrok_shim_script(riabuild, ngrok)).await
}

/// `~/.riabuild/bin/infisical` — infisical, signed in to the team's project for
/// the length of one command.
///
/// The second entry in `bin/` that is not an `exec` line, and it exists for the
/// reason `env_local` already gives: riabuild fills `.env.dev` with a
/// short-lived credential brokered from riabuild-web and written down nowhere,
/// and the developer who then typed `infisical export` themselves met a CLI
/// that had never been logged in. `infisical login` is not the answer to that —
/// it stores a credential on the machine, which is the one thing the brokering
/// design exists to avoid — so a developer's own invocation gets exactly what
/// riabuild's does: a credential minted for this command, handed over in the
/// environment, and left to expire.
///
/// **Unlike ngrok's, this shim carries nothing itself.** ngrok needs one value
/// and takes it through a command substitution. infisical needs five — the
/// token, the API URL, the project, the environment and the secret path — and
/// getting five back into a POSIX shell means either an `eval` of what the
/// server said or a here-document, which most shells implement as a temporary
/// *file*. A brokered credential in `/tmp`, however briefly, is the thing this
/// whole path exists to prevent. So riabuild fetches them and starts infisical
/// itself, and the credential exists in two process environments and nowhere
/// else.
///
/// riabuild is named in full because it is not on `PATH`, and infisical is not
/// named at all: `internal infisical` resolves the versioned copy through
/// `Ctx::infisical` like every other riabuild call, so "which infisical" has one
/// answer rather than two that can disagree after an upgrade.
pub fn infisical_shim_script(riabuild: &Path, _infisical: &Path) -> String {
    format!(
        r#"#!/bin/sh
# Generated by riabuild. Edits here are overwritten.
#
# Runs the infisical riabuild installed, against the team's project, with a
# short-lived credential brokered from riabuild-web for this one command and
# stored nowhere on this machine. riabuild fetches the credential and passes it
# in the environment of the process it starts, never in an argument, because
# `ps` shows argument lists to every account on the machine.
#
# A fetch that fails says so on stderr and runs infisical anyway, so `infisical
# --version` and `infisical scan` still work on a machine with no network.
exec {riabuild} internal infisical "$@"
"#,
        riabuild = shell_quote(&riabuild.to_string_lossy()),
    )
}

/// The tool riabuild shadows to send links to the laptop.
///
/// Named separately from `CLIPBOARD_TOOLS` because it is a different shim with
/// a different contract: the clipboard shims hand unrecognised invocations to
/// the real binary, and this one never does.
pub const BROWSER_TOOL: &str = "xdg-open";

/// What `riabuild agents` is called by the developer who uses it.
pub const AGENTS_TOOL: &str = "agents";

/// `~/.riabuild/bin/agents`.
///
/// The whole of how the feature gets its own executable name. The alternative —
/// a second binary in the workspace — would mean a `[[bin]]` in `crates/cli`,
/// an install line in the Homebrew formula, the deb and the rpm, and a second
/// artefact for `release.yml` to build, sign and strip. This is one generated
/// file in a directory riabuild already owns and already puts at the front of
/// `PATH`, and it can never disagree with the binary it came from because it
/// names it by absolute path.
pub async fn write_agents_shim(ctx: &Ctx, riabuild: &Path) -> Result<()> {
    let bin = ctx.paths.bin_dir();
    write_script(&bin, AGENTS_TOOL, &agents_shim_script(riabuild)).await
}

/// The script [`write_agents_shim`] writes.
pub fn agents_shim_script(riabuild: &Path) -> String {
    format!(
        r#"#!/bin/sh
# Generated by riabuild. Edits here are overwritten.
#
# Opens the agents window: Claude Code, Codex and Grok Build sessions together.
#
# riabuild is named in full because it is not on PATH: it lives in its own
# versioned directory, and a bare name would find another machine's copy or
# none at all.
exec {riabuild} agents "$@"
"#,
        riabuild = shell_quote(&riabuild.to_string_lossy()),
    )
}

/// `~/.riabuild/bin/xdg-open`.
///
/// Written on the *server*, beside the clipboard shims and for the same reason:
/// `~/.riabuild/bin` leads `PATH` there, so this is what `gh auth login` finds.
/// Claude Code needs `BROWSER` pointing here as well — see `shims::browser` for
/// why `PATH` alone does not reach it.
///
/// Written beside `write_clipboard_shims` and under the same condition. It has
/// to be: `BROWSER` is exported by exactly that condition, and a `BROWSER`
/// pointing at a shim nobody wrote fails a sign-in outright instead of falling
/// back to printing the URL.
pub async fn write_browser_shim(ctx: &Ctx, riabuild: &Path) -> Result<()> {
    let bin = ctx.paths.bin_dir();
    write_script(&bin, BROWSER_TOOL, &browser_shim_script(riabuild)).await
}

/// `~/.riabuild/bin/xdg-open`.
pub fn browser_shim_script(riabuild: &Path) -> String {
    format!(
        r#"#!/bin/sh
# Generated by riabuild. Edits here are overwritten.
#
# Opens links in the browser on the developer's laptop, over the riabuild
# channel. Deliberately does NOT fall back to the real {BROWSER_TOOL}: on a
# server with no display that resolves to a terminal browser, which then
# renders inside this session's own TTY.
#
# riabuild is named in full because it is not on PATH: it lives in its own
# versioned directory, and a bare name would find another machine's copy or
# none at all.
exec {riabuild} channel open "$@"
"#,
        riabuild = shell_quote(&riabuild.to_string_lossy()),
    )
}

/// The riabuild that is running, by absolute path — what every generated shim
/// has to name.
///
/// Resolved once, by the caller that writes the shims, rather than inside each
/// writer: a run that cannot answer this question must fail before it writes
/// the first shim, not after it has written three good ones and a broken one.
///
/// This is `/proc/self/exe` on Linux, so it survives the developer's `PATH`,
/// the launcher's `PATH` strip, and a `$BROWSER` invoked from a process that
/// sanitised the environment. It follows a self-update too: `upgrade_and_reexec`
/// replaces this process before provisioning reaches here, so what gets written
/// is the version that will actually be running.
pub fn running_binary() -> Result<std::path::PathBuf> {
    std::env::current_exe()
        .context("riabuild could not work out the path to its own binary, so the clipboard and browser shims would have had to guess at it")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::testing::ctx_with;
    use riabuild_runner::FakeRunner;

    #[test]
    fn the_pnpm_shim_starts_the_launcher_in_its_own_tree() {
        let shim = exec_shim(Path::new("/Users/ada/.riabuild/pnpm/11.11.0/pnpm"));
        assert!(shim.starts_with("#!/bin/sh\n"), "{shim}");
        // The launcher is started where its `dist/` tree is, not copied out of
        // it — pnpm 11 loads `dist/pnpm.mjs` from beside its own executable.
        assert!(
            shim.contains(r#"exec '/Users/ada/.riabuild/pnpm/11.11.0/pnpm' "$@""#),
            "{shim}"
        );
    }

    #[tokio::test]
    async fn a_tool_shim_points_at_the_versioned_copy_and_is_executable() {
        // This is what puts riabuild's gh in front of a system one on PATH.
        let (ctx, home) = ctx_with(FakeRunner::new()).await;
        let binary = home.path().join(".riabuild/gh/2.97.0/bin/gh");
        write_tool(&ctx, "gh", &binary).await.unwrap();
        // Safe to run twice, like every other apply().
        write_tool(&ctx, "gh", &binary).await.unwrap();

        let shim = ctx.paths.bin_dir().join("gh");
        let script = tokio::fs::read_to_string(&shim).await.unwrap();
        assert!(script.contains("gh/2.97.0/bin/gh"), "{script}");
        assert!(script.contains(r#""$@""#), "{script}");
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = tokio::fs::metadata(&shim)
                .await
                .unwrap()
                .permissions()
                .mode();
            assert_eq!(mode & 0o111, 0o111, "mode was {mode:o}");
        }
    }

    /// The path a server actually reaches riabuild by: a versioned directory
    /// that nothing puts on `PATH`.
    fn server_binary() -> &'static Path {
        Path::new("/home/dev/.riabuild/riabuild/2026.08.14/riabuild")
    }

    #[tokio::test]
    async fn the_clipboard_shims_route_through_riabuild() {
        let (ctx, _home) = ctx_with(FakeRunner::new()).await;
        write_clipboard_shims(&ctx, server_binary()).await.unwrap();
        // Safe to run twice, like every other apply().
        write_clipboard_shims(&ctx, server_binary()).await.unwrap();

        for tool in CLIPBOARD_TOOLS {
            let script = tokio::fs::read_to_string(ctx.paths.bin_dir().join(tool))
                .await
                .unwrap();
            assert!(script.contains("channel shim"), "{script}");
            assert!(script.contains(tool), "{script}");
            // Arguments must reach the tool, or the TARGETS probe loses its
            // flags and every paste silently fails.
            assert!(script.contains(r#""$@""#), "{script}");
        }
    }

    #[tokio::test]
    async fn the_browser_shim_routes_through_riabuild() {
        let (ctx, _home) = ctx_with(FakeRunner::new()).await;
        write_browser_shim(&ctx, server_binary()).await.unwrap();
        // Safe to run twice, like every other apply().
        write_browser_shim(&ctx, server_binary()).await.unwrap();

        let script = tokio::fs::read_to_string(ctx.paths.bin_dir().join(BROWSER_TOOL))
            .await
            .unwrap();
        assert!(script.contains("channel open"), "{script}");
        assert!(script.contains(r#""$@""#), "{script}");
        // The whole point. A fallback to the real xdg-open on a display-less
        // server runs a terminal browser inside the session's own TTY, which is
        // the failure this shim exists to prevent.
        assert!(!script.contains("exec xdg-open"), "{script}");
    }

    /// The bug this pins: every shim used to `exec riabuild …` by bare name,
    /// and riabuild is the one tool riabuild does not put on `PATH` — it lives
    /// in a versioned directory, and `shell::riabuild_path_dirs` leads `PATH`
    /// with `bin/` and Node's `bin/` alone. On a server with no other copy the
    /// developer got `xdg-open: exec: riabuild: not found` and no browser; on a
    /// server with an apt or Homebrew copy, worse, because it worked — as some
    /// other version, against a channel this session owns.
    ///
    /// Asserted over every generated shim at once rather than one at a time, so
    /// that a shim added later is covered by this test on the day it is written
    /// rather than the day someone remembers to extend it.
    #[test]
    fn no_shim_looks_riabuild_up_on_the_path() {
        let scripts = CLIPBOARD_TOOLS
            .iter()
            .map(|tool| clipboard_shim_script(server_binary(), tool))
            .chain(std::iter::once(browser_shim_script(server_binary())))
            .chain(std::iter::once(infisical_shim_script(
                server_binary(),
                Path::new("/home/dev/.riabuild/infisical/0.43.120/infisical"),
            )));

        for script in scripts {
            let execs: Vec<&str> = script
                .lines()
                .map(str::trim)
                .filter(|line| line.starts_with("exec "))
                .collect();
            assert_eq!(execs.len(), 1, "{script}");
            assert!(
                execs[0].starts_with(&format!("exec '{}' ", server_binary().display())),
                "{script}"
            );
        }
    }

    /// The path is taken from the running process, so it is right on a laptop,
    /// on a server, and after a self-update re-exec — none of which a test can
    /// stand in for. What it can pin is that the answer is absolute, which is
    /// the whole property the shims need.
    #[test]
    fn the_binary_the_shims_name_is_an_absolute_path() {
        let binary = running_binary().expect("the test binary has a path");
        assert!(binary.is_absolute(), "{}", binary.display());
    }

    #[test]
    fn the_ngrok_shim_names_both_binaries_in_full() {
        // riabuild is not on `PATH` and ngrok is deliberately not either: the
        // shim *is* what `PATH` finds. A bare name in here would find the shim
        // itself, or another machine's riabuild.
        let script = ngrok_shim_script(
            server_binary(),
            Path::new("/home/dev/.riabuild/ngrok/3.39.11/ngrok"),
        );
        assert!(
            script.contains(&format!(
                "exec '{}' internal ngrok --binary '/home/dev/.riabuild/ngrok/3.39.11/ngrok' -- \"$@\"",
                server_binary().display()
            )),
            "{script}"
        );
        for line in script.lines().map(str::trim) {
            assert!(
                !line.starts_with("exec riabuild") && !line.starts_with("exec ngrok"),
                "{line}"
            );
        }
    }

    #[test]
    fn the_ngrok_shim_keeps_the_token_out_of_the_file_and_out_of_every_argument_list() {
        // `ps` is world-readable, and on a shared server it shows every other
        // developer's command lines. The token reaches ngrok through the
        // environment or not at all — and it is fetched by the process that
        // *becomes* ngrok, so it is never a shell variable either.
        let script = ngrok_shim_script(
            server_binary(),
            Path::new("/home/dev/.riabuild/ngrok/3.39.11/ngrok"),
        );
        assert!(!script.contains("--authtoken"), "{script}");
        assert!(!script.contains("config add-authtoken"), "{script}");
        assert!(!script.contains("NGROK_AUTHTOKEN"), "{script}");
        // And no command substitution. The shim used to read the token off
        // `internal ngrok-token`'s stdout, which made "print nothing else on
        // stdout" a rule the whole of that subcommand had to keep, and put a
        // credential in a shell variable in a process that then went on to
        // `exec`.
        assert!(!script.contains("$("), "{script}");
    }

    /// The property the whole of `~/.riabuild/bin` is held to.
    ///
    /// Every generated file here is a shebang, some comments, and exactly one
    /// `exec`. A branch, a substitution, a pipeline or a `set --` appearing in
    /// one of them means a decision has leaked back out of Rust and into a
    /// language with no type checker and no test that runs without a
    /// subprocess — which is how the `PATH` strip, the `case "$PWD"` and the
    /// approval-policy scans came to be shell in the first place.
    ///
    /// Asserted over every generator at once, so one added later is covered on
    /// the day it is written rather than the day someone remembers to extend
    /// this.
    #[test]
    fn every_generated_script_is_a_single_exec() {
        let riabuild = server_binary();
        let ngrok = Path::new("/home/dev/.riabuild/ngrok/3.39.11/ngrok");
        let node = Path::new("/home/dev/.riabuild/node/22.23.1/bin/node");
        let checkout = std::path::PathBuf::from("/home/dev/Clubria/ai-builders-hub");

        let mut scripts = vec![
            exec_shim(ngrok),
            node_shim(
                node,
                Path::new("/home/dev/.riabuild/pnpm/11.11.0/bin/pnpm.cjs"),
            ),
            ngrok_shim_script(riabuild, ngrok),
            infisical_shim_script(
                riabuild,
                Path::new("/home/dev/.riabuild/infisical/0.43.120/infisical"),
            ),
            browser_shim_script(riabuild),
            agents_shim_script(riabuild),
            claude::launcher_script(
                riabuild,
                Path::new("/home/dev/.riabuild/claude/abc"),
                "/home/dev/.riabuild/node/22.23.1/bin/claude",
                Path::new("/home/dev/.riabuild/org-settings.json"),
                Path::new("/home/dev/.riabuild/bin"),
                std::slice::from_ref(&checkout),
                Some(&checkout),
            ),
            codex::launcher_script(
                riabuild,
                Path::new("/home/dev/.riabuild/codex/1"),
                "/home/dev/.riabuild/node/22.23.1/bin/codex",
                Path::new("/home/dev/.riabuild/bin"),
            ),
            grok::launcher_script(
                riabuild,
                Path::new("/home/dev/.riabuild/grok/1"),
                "/home/dev/.riabuild/grok/1.0.5/grok",
                Path::new("/home/dev/.riabuild/bin"),
            ),
        ];
        scripts.extend(
            CLIPBOARD_TOOLS
                .iter()
                .map(|tool| clipboard_shim_script(riabuild, tool)),
        );

        for script in scripts {
            assert!(script.starts_with("#!/bin/sh\n"), "{script}");
            let code: Vec<&str> = script
                .lines()
                .map(str::trim)
                .filter(|line| !line.is_empty() && !line.starts_with('#'))
                .collect();
            assert_eq!(code.len(), 1, "{script}");
            assert!(code[0].starts_with("exec "), "{script}");
            for forbidden in [
                "if ", "case ", "for ", "while ", "set --", "$(", "|", "&&", ";",
            ] {
                assert!(
                    !code[0].contains(forbidden),
                    "`{forbidden}` in a generated script:\n{script}"
                );
            }
            // The developer's own arguments reach the far side, every time.
            assert!(code[0].ends_with(r#""$@""#), "{script}");
        }
    }

    /// The infisical binary is riabuild's to resolve, not the shim's to name.
    ///
    /// `internal infisical` asks `Ctx::infisical` for it, which is the same
    /// question every other riabuild call asks. A path baked in here would be a
    /// second answer, and the two disagree for as long as it takes a version
    /// bump to rewrite this file.
    #[test]
    fn the_infisical_shim_hands_the_whole_invocation_to_riabuild() {
        let script = infisical_shim_script(
            server_binary(),
            Path::new("/home/dev/.riabuild/infisical/0.43.120/infisical"),
        );
        assert!(
            script.contains(&format!(
                r#"exec {} internal infisical "$@""#,
                shell_quote(&server_binary().to_string_lossy())
            )),
            "{script}"
        );
        assert!(!script.contains("0.43.120"), "{script}");
    }

    /// Nothing in this script may hold the credential, which is the whole
    /// reason it is four lines rather than ngrok's twelve.
    ///
    /// Five values would have to come back from riabuild as text, and both
    /// shapes for reading text into a POSIX shell are worse than the problem:
    /// an `eval` of what the server said, or a here-document, which dash and
    /// most other shells write to a file in `/tmp` first.
    #[test]
    fn the_infisical_shim_never_handles_the_credential_itself() {
        let script = infisical_shim_script(
            server_binary(),
            Path::new("/home/dev/.riabuild/infisical/0.43.120/infisical"),
        );
        assert!(!script.contains("INFISICAL_TOKEN"), "{script}");
        assert!(!script.contains("eval"), "{script}");
        assert!(!script.contains("<<"), "{script}");
        assert!(!script.contains("$("), "{script}");
    }

    /// A shadowed binary with no parser behind it would pass everything through
    /// — a tool that looks installed and does nothing riabuild intended.
    #[test]
    fn every_shadowed_tool_has_a_parser() {
        for tool in CLIPBOARD_TOOLS {
            assert!(
                clipboard::Tool::from_name(tool).is_some(),
                "{tool} is shimmed but the shim cannot parse it"
            );
        }
    }
}
