//! `~/.riabuild/bin` — the small scripts that make the environment work.
//!
//! The important ones are the Claude Code launchers: `claude` runs the primary
//! account, and `claude-1` … `claude-N` each run their own. Every one launches
//! Claude Code with that account's config directory and the org settings
//! layered over it.
//!
//! ```sh
//! CLAUDE_CONFIG_DIR=~/.riabuild/claude/<uuid> claude --settings ~/.riabuild/org-settings.json
//! ```
//!
//! `--settings` layers over the account's own settings, so org policy is always
//! current, removals take effect, and developer edits survive. Nothing is merged
//! into anyone's `settings.json`.
//!
//! `CLAUDE_CONFIG_DIR` is present in the Claude Code binary (verified against
//! 2.1.221) but is **not** in the public settings documentation. Undocumented
//! means unpromised, so the four `#[ignore]`d smoke tests at the end of this
//! file pin it and the three behaviours built on it: an upstream change should
//! surface as a test failure, not as broken laptops. They need a real Claude Code
//! install, so run them with `cargo test -- --ignored` before every version bump.
//!
//! The launchers also clear `SSH_CONNECTION`, `SSH_CLIENT` and `SSH_TTY`, which
//! is what makes the clipboard shims below reachable — see the comment in
//! `launcher_script`. That is undocumented behaviour too, read out of the 2.1.224
//! binary rather than promised anywhere, but it cannot be pinned by a smoke test:
//! Claude Code exposes no non-interactive clipboard command to assert against.
//! Re-read it by hand when the pinned Claude Code version moves.

pub mod browser;
pub mod clipboard;

use crate::Ctx;
use anyhow::Result;
use riabuild_fetch::archive::make_executable;
use std::path::Path;

/// One account's launcher: `claude`, or `claude-<n>`.
pub fn launcher_script(
    config_dir: &Path,
    claude: &str,
    org_settings: &Path,
    bin_dir: &Path,
) -> String {
    format!(
        r#"#!/bin/sh
# Generated by riabuild. Edits here are overwritten.
#
# Launches Claude Code with one account's config directory and the team's
# settings layered on top. --settings wins over the account's own settings,
# which is how org policy stays current without riabuild ever editing
# settings.json.
set -e
# Claude Code treats "am I over SSH?" as "my clipboard is not the user's
# clipboard", and answers it from these three variables alone. Over SSH it skips
# the native copy and returns "" from every paste *without running anything* — so
# the xclip/wl-paste shims in this same bin/ are never reached, and the channel
# they front is dead code. Clearing the three makes Claude Code probe for a
# clipboard tool, find riabuild's shim first on PATH, and reach the laptop.
#
# Verified against Claude Code 2.1.224: only SSH_CONNECTION reaches the clipboard
# path, but all three feed the terminal-type probe, so a session that cleared one
# and kept the others would still report itself as "ssh-session". They are also
# on Claude Code's own environment allowlist, so a relaunched or child session
# inherits whatever this script leaves — clearing them here covers the whole tree.
#
# SSH_AUTH_SOCK is deliberately NOT cleared: it is agent forwarding, not session
# detection, and dropping it breaks `git push` over SSH.
unset SSH_CONNECTION SSH_CLIENT SSH_TTY
CLAUDE_CONFIG_DIR="{config_dir}"
export CLAUDE_CONFIG_DIR
claude_binary="{claude}"
case "$claude_binary" in
  /*) ;;
  # A non-absolute path (no Node pinned yet) can't be trusted with the -x
  # test below: a same-named executable in the current directory would pass
  # it, skip the PATH strip, and exec a bare name that PATH search resolves
  # straight back to this script. Treat it as no path at all.
  *) claude_binary="" ;;
esac
if [ ! -x "$claude_binary" ]; then
  # The recorded binary is gone: a `claude update` that migrated to a native
  # install, or a Node version change since the last run. Fall back to PATH
  # with riabuild's own bin/ removed — without that this script finds itself,
  # because bin/ comes first inside the environment shell.
  PATH=$(printf '%s' "$PATH" | tr ':' '\n' | grep -vxF "{bin_dir}" | paste -sd: -)
  export PATH
  claude_binary=claude
fi
if [ -f "{settings}" ]; then
  exec "$claude_binary" --settings "{settings}" "$@"
fi
exec "$claude_binary" "$@"
"#,
        config_dir = config_dir.display(),
        bin_dir = bin_dir.display(),
        settings = org_settings.display(),
    )
}

/// `~/.riabuild/bin/<name>`, handing off to a binary in its own versioned tree.
///
/// Used for pnpm, `gh`, and `infisical` alike. pnpm is the one that *requires*
/// it: pnpm 11 loads `dist/` from beside its executable, so copying the
/// executable onto `PATH` by itself gets `Cannot find module
/// .../dist/pnpm.mjs`. A symlink also works today, because Node resolves
/// `process.execPath` through symlinks, but that is an implementation detail of
/// the runtime pnpm happens to be built on.
///
/// `gh` and `infisical` are single static binaries that could be copied, and
/// use a shim anyway so that `bin/` is uniformly a directory of small scripts
/// and a version bump rewrites one line instead of moving 30 MB.
pub fn exec_shim(binary: &Path) -> String {
    format!(
        r#"#!/bin/sh
# Generated by riabuild. Edits here are overwritten.
exec "{binary}" "$@"
"#,
        binary = binary.display(),
    )
}

/// Writes `~/.riabuild/bin/<name>` for one owned tool.
///
/// This is what puts the owned copy in front of any system one for the
/// developer's own commands: `~/.riabuild/bin` is first on `PATH` inside the
/// environment shell. riabuild's own calls do not rely on it — they run the
/// versioned path directly, because during provisioning that `PATH` does not
/// exist yet.
pub async fn write_tool(ctx: &Ctx, name: &str, binary: &Path) -> Result<()> {
    let bin = ctx.paths.bin_dir();
    tokio::fs::create_dir_all(&bin).await?;
    let shim = bin.join(name);
    riabuild_paths::config::write_atomic(&shim, exec_shim(binary).as_bytes()).await?;
    make_executable(&shim).await?;
    Ok(())
}

/// The tools riabuild shadows in `~/.riabuild/bin`.
///
/// One per direction per session type: xclip does both on X11, and Wayland
/// splits them across wl-paste and wl-copy. Every name here must also be a
/// `Tool` the shim can parse — one without a parser would shadow a working
/// binary with one that passes everything through.
pub const CLIPBOARD_TOOLS: &[&str] = &["xclip", "wl-paste", "wl-copy"];

/// `~/.riabuild/bin/xclip`, `wl-paste` and `wl-copy`.
///
/// All three route into riabuild, which decides whether the invocation is a
/// clipboard transfer to send down the channel or something to hand to the real
/// binary. They are written on the *server*, where `~/.riabuild/bin` leads
/// `PATH` and Claude Code's probe finds them first.
///
/// Written by `provision::write_launchers`, under the same condition
/// `shell::browser_for` uses to export `BROWSER` — see the note there for why
/// the two must not drift apart.
pub async fn write_clipboard_shims(ctx: &Ctx) -> Result<()> {
    let bin = ctx.paths.bin_dir();
    tokio::fs::create_dir_all(&bin).await?;

    // One per direction per session type: xclip does both on X11, and Wayland
    // splits them across wl-paste and wl-copy.
    for tool in CLIPBOARD_TOOLS {
        let script = format!(
            r#"#!/bin/sh
# Generated by riabuild. Edits here are overwritten.
#
# Carries the clipboard between this server and the laptop over the riabuild
# channel. Anything that is not a clipboard transfer is handed to the real
# {tool} on PATH.
exec riabuild channel shim {tool} "$@"
"#
        );
        let path = bin.join(tool);
        riabuild_paths::config::write_atomic(&path, script.as_bytes()).await?;
        make_executable(&path).await?;
    }
    Ok(())
}

/// The tool riabuild shadows to send links to the laptop.
///
/// Named separately from `CLIPBOARD_TOOLS` because it is a different shim with
/// a different contract: the clipboard shims hand unrecognised invocations to
/// the real binary, and this one never does.
pub const BROWSER_TOOL: &str = "xdg-open";

/// `~/.riabuild/bin/xdg-open`.
///
/// Written on the *server*, beside the clipboard shims and for the same reason:
/// `~/.riabuild/bin` leads `PATH` there, so this is what `gh auth login` finds.
/// Claude Code needs `BROWSER` pointing here as well — see `shims::browser` for
/// why `PATH` alone does not reach it.
///
/// Written beside `write_clipboard_shims` and under the same condition. It has
/// to be: `BROWSER` is exported by exactly that condition, and a `BROWSER`
/// pointing at a shim nobody wrote fails a sign-in outright instead of falling
/// back to printing the URL.
pub async fn write_browser_shim(ctx: &Ctx) -> Result<()> {
    let bin = ctx.paths.bin_dir();
    tokio::fs::create_dir_all(&bin).await?;

    let script = format!(
        r#"#!/bin/sh
# Generated by riabuild. Edits here are overwritten.
#
# Opens links in the browser on the developer's laptop, over the riabuild
# channel. Deliberately does NOT fall back to the real {BROWSER_TOOL}: on a
# server with no display that resolves to a terminal browser, which then
# renders inside this session's own TTY.
exec riabuild channel open "$@"
"#
    );
    let path = bin.join(BROWSER_TOOL);
    riabuild_paths::config::write_atomic(&path, script.as_bytes()).await?;
    make_executable(&path).await?;
    Ok(())
}

pub async fn write_all(ctx: &Ctx) -> Result<()> {
    let bin = ctx.paths.bin_dir();
    tokio::fs::create_dir_all(&bin).await?;

    let claude = ctx.claude();
    let settings = ctx.paths.org_settings_file();
    let ids = &ctx.config.claude_accounts;

    for (index, id) in ids.iter().enumerate() {
        let script = launcher_script(&ctx.paths.claude_profile_dir(id), &claude, &settings, &bin);
        write_launcher(&bin.join(format!("claude-{}", index + 1)), &script).await?;
        if index == 0 {
            write_launcher(&bin.join("claude"), &script).await?;
        }
    }

    prune(&bin, ids.len()).await?;
    Ok(())
}

/// Landed by rename, like every other file riabuild generates.
///
/// Launcher content is deterministic given the account list, so two concurrent
/// writers agree and no lock is needed here — the hazard is only an interrupt
/// landing mid-write, which leaves a truncated `claude-2` that fails with a
/// shell syntax error.
async fn write_launcher(path: &Path, script: &str) -> Result<()> {
    riabuild_paths::config::write_atomic(path, script.as_bytes()).await?;
    make_executable(path).await?;
    Ok(())
}

/// Removes launchers that no longer name an account.
///
/// A file that was never there is the state being asked for, so
/// `NotFound` is swallowed. Anything else — `EPERM`, a read-only mount — is
/// a real failure: silently swallowing it would leave an orphan launcher
/// behind unreported.
async fn prune(bin: &Path, count: usize) -> Result<()> {
    // `c` is what riabuild called the launcher before accounts existed.
    remove_if_present(&bin.join("c")).await?;
    if count == 0 {
        remove_if_present(&bin.join("claude")).await?;
    }
    for number in count + 1..=crate::accounts::MAX {
        remove_if_present(&bin.join(format!("claude-{number}"))).await?;
    }
    Ok(())
}

async fn remove_if_present(path: &Path) -> Result<()> {
    match tokio::fs::remove_file(path).await {
        Ok(()) => Ok(()),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(error) => Err(error.into()),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::accounts;
    use crate::testing::ctx_with;
    use riabuild_runner::FakeRunner;

    #[test]
    fn the_pnpm_shim_starts_the_launcher_in_its_own_tree() {
        let shim = exec_shim(Path::new("/Users/ada/.riabuild/pnpm/11.11.0/pnpm"));
        assert!(shim.starts_with("#!/bin/sh\n"), "{shim}");
        // The launcher is started where its `dist/` tree is, not copied out of
        // it — pnpm 11 loads `dist/pnpm.mjs` from beside its own executable.
        assert!(
            shim.contains(r#"exec "/Users/ada/.riabuild/pnpm/11.11.0/pnpm" "$@""#),
            "{shim}"
        );
    }

    fn script() -> String {
        launcher_script(
            Path::new("/Users/ada/.riabuild/claude/11111111-2222-4333-8444-555555555555"),
            "/Users/ada/.riabuild/node/22.23.1/bin/claude",
            Path::new("/Users/ada/.riabuild/org-settings.json"),
            Path::new("/Users/ada/.riabuild/bin"),
        )
    }

    #[test]
    fn the_launcher_sets_the_account_and_layers_org_settings() {
        let script = script();
        assert!(script.starts_with("#!/bin/sh"));
        assert!(script.contains(
            r#"CLAUDE_CONFIG_DIR="/Users/ada/.riabuild/claude/11111111-2222-4333-8444-555555555555""#
        ));
        assert!(script.contains(r#"--settings "/Users/ada/.riabuild/org-settings.json""#));
        // Arguments must reach claude, or `claude-2 --resume` silently loses
        // them — and `claude-2 auth login`, which the account box tells the
        // developer to run, would do nothing at all.
        assert!(script.contains(r#""$@""#));
        // A dropped `export` would leave every account sharing the default
        // config directory — all nine collapsing into one — with the rest of
        // this test still green.
        assert!(script.contains("export CLAUDE_CONFIG_DIR"));
    }

    #[test]
    fn the_launcher_clears_the_ssh_detection_variables() {
        let script = script();
        // Assert on the `unset` lines themselves, not on the script text: the
        // comment above them names SSH_AUTH_SOCK to explain why it is spared,
        // so a substring search over the whole script proves nothing.
        let unsets: Vec<&str> = script
            .lines()
            .map(str::trim)
            .filter(|line| line.starts_with("unset "))
            .collect();
        // Claude Code answers "am I over SSH?" from these three and nothing
        // else. Leave any of them set and every paste returns "" without a
        // subprocess, so the xclip/wl-paste shims beside this launcher are
        // never invoked and the channel behind them is unreachable.
        //
        // Agent forwarding is not session detection: a fourth name here, or
        // SSH_AUTH_SOCK joining this line, breaks `git push` over SSH.
        assert_eq!(
            unsets,
            ["unset SSH_CONNECTION SSH_CLIENT SSH_TTY"],
            "{script}"
        );
        // A clear that lands after the exec never runs.
        let unset = script.find("unset SSH_CONNECTION").unwrap();
        let exec = script.find("exec ").unwrap();
        assert!(unset < exec, "unset must precede every exec:\n{script}");
    }

    #[test]
    fn the_launcher_can_never_exec_itself() {
        // `~/.riabuild/bin` is first on PATH, so a script called `claude` that
        // runs `exec claude` finds itself and forks until the shell dies.
        let script = script();
        assert!(!script.contains("exec claude"), "{script}");
        assert!(
            script.contains(r#"claude_binary="/Users/ada/.riabuild/node/22.23.1/bin/claude""#),
            "{script}"
        );
        assert!(script.contains(r#"exec "$claude_binary""#), "{script}");
    }

    #[test]
    fn a_binary_that_moved_is_found_without_riabuilds_own_bin() {
        // `claude update` can migrate to a native install, which leaves the
        // recorded path dangling until the next `riabuild`. A dead `claude`
        // command reads as Claude Code being uninstalled.
        let script = script();
        assert!(
            script.contains(r#"if [ ! -x "$claude_binary" ]"#),
            "{script}"
        );
        assert!(
            script.contains(r#"grep -vxF "/Users/ada/.riabuild/bin""#),
            "{script}"
        );
        // `tr '\n' ':'` would leave a trailing colon, and an empty PATH entry
        // means the current directory.
        assert!(script.contains("paste -sd: -"), "{script}");
    }

    #[test]
    fn the_launcher_still_works_before_settings_have_been_fetched() {
        let script = script();
        assert!(script.contains(r#"if [ -f "/Users/ada/.riabuild/org-settings.json" ]"#));
        // The unconditional exec after the `if` is what runs on every machine
        // that has not fetched settings yet. Losing it would still satisfy
        // `the_launcher_can_never_exec_itself` (which only checks the exec
        // inside the `if`) while the launcher silently exited 0 doing nothing.
        assert!(script.contains(r#"exec "$claude_binary" "$@""#), "{script}");
    }

    #[test]
    fn a_bare_binary_name_cannot_be_used_to_exec_itself() {
        // `Ctx::claude()` returns the bare name "claude" before a Node
        // version is pinned. `[ ! -x "claude" ]` is a cwd-relative test — a
        // same-named executable in an untrusted checkout would pass it, skip
        // the PATH strip, and `exec "claude"` would search PATH straight back
        // to this same script.
        let script = launcher_script(
            Path::new("/Users/ada/.riabuild/claude/11111111-2222-4333-8444-555555555555"),
            "claude",
            Path::new("/Users/ada/.riabuild/org-settings.json"),
            Path::new("/Users/ada/.riabuild/bin"),
        );
        assert!(script.contains(r#"case "$claude_binary" in"#), "{script}");
        assert!(script.contains(r#"*) claude_binary="" ;;"#), "{script}");
    }

    #[tokio::test]
    async fn every_account_gets_a_launcher_and_the_first_gets_two() {
        let (mut ctx, _home) = ctx_with(FakeRunner::new()).await;
        let ids = vec![accounts::new_id(), accounts::new_id(), accounts::new_id()];
        ctx.config.claude_accounts = ids.clone();

        write_all(&ctx).await.unwrap();
        // Safe to run twice, like every other apply().
        write_all(&ctx).await.unwrap();

        let bin = ctx.paths.bin_dir();
        for (index, id) in ids.iter().enumerate() {
            let script = tokio::fs::read_to_string(bin.join(format!("claude-{}", index + 1)))
                .await
                .unwrap();
            assert!(script.contains(id.as_str()), "claude-{}", index + 1);
        }
        let primary = tokio::fs::read_to_string(bin.join("claude")).await.unwrap();
        assert!(primary.contains(ids[0].as_str()), "{primary}");

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = tokio::fs::metadata(bin.join("claude"))
                .await
                .unwrap()
                .permissions()
                .mode();
            // A dropped `make_executable` reads as "permission denied" on a
            // developer's laptop, not as a test failure in CI.
            assert_eq!(mode & 0o111, 0o111, "mode was {mode:o}");
        }
    }

    #[tokio::test]
    async fn launchers_for_accounts_that_are_gone_are_removed() {
        // An orphan is worse than a missing shim: it points at a deleted
        // directory, so Claude Code makes it afresh, asks for a login, and
        // leaves an account no riabuild command can see.
        let (mut ctx, _home) = ctx_with(FakeRunner::new()).await;
        ctx.config.claude_accounts = vec![accounts::new_id(), accounts::new_id()];
        write_all(&ctx).await.unwrap();

        let bin = ctx.paths.bin_dir();
        // An older riabuild's launcher, and a third account since deleted.
        tokio::fs::write(bin.join("c"), "#!/bin/sh\n")
            .await
            .unwrap();
        tokio::fs::write(bin.join("claude-3"), "#!/bin/sh\n")
            .await
            .unwrap();

        ctx.config.claude_accounts.truncate(1);
        write_all(&ctx).await.unwrap();

        assert!(tokio::fs::try_exists(bin.join("claude-1")).await.unwrap());
        assert!(!tokio::fs::try_exists(bin.join("claude-2")).await.unwrap());
        assert!(!tokio::fs::try_exists(bin.join("claude-3")).await.unwrap());
        assert!(!tokio::fs::try_exists(bin.join("c")).await.unwrap());

        // Deleting the last account must take the primary `claude` launcher
        // with it — the `count == 0` branch of `prune`, otherwise untested.
        ctx.config.claude_accounts.clear();
        write_all(&ctx).await.unwrap();
        assert!(!tokio::fs::try_exists(bin.join("claude")).await.unwrap());
        assert!(!tokio::fs::try_exists(bin.join("claude-1")).await.unwrap());
    }

    #[tokio::test]
    async fn a_tool_shim_points_at_the_versioned_copy_and_is_executable() {
        // This is what puts riabuild's gh in front of a system one on PATH.
        let (ctx, home) = ctx_with(FakeRunner::new()).await;
        let binary = home.path().join(".riabuild/gh/2.97.0/bin/gh");
        write_tool(&ctx, "gh", &binary).await.unwrap();
        // Safe to run twice, like every other apply().
        write_tool(&ctx, "gh", &binary).await.unwrap();

        let shim = ctx.paths.bin_dir().join("gh");
        let script = tokio::fs::read_to_string(&shim).await.unwrap();
        assert!(script.contains("gh/2.97.0/bin/gh"), "{script}");
        assert!(script.contains(r#""$@""#), "{script}");
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = tokio::fs::metadata(&shim)
                .await
                .unwrap()
                .permissions()
                .mode();
            assert_eq!(mode & 0o111, 0o111, "mode was {mode:o}");
        }
    }

    #[tokio::test]
    async fn the_clipboard_shims_route_through_riabuild() {
        let (ctx, _home) = ctx_with(FakeRunner::new()).await;
        write_clipboard_shims(&ctx).await.unwrap();
        // Safe to run twice, like every other apply().
        write_clipboard_shims(&ctx).await.unwrap();

        for tool in CLIPBOARD_TOOLS {
            let script = tokio::fs::read_to_string(ctx.paths.bin_dir().join(tool))
                .await
                .unwrap();
            assert!(script.contains("channel shim"), "{script}");
            assert!(script.contains(tool), "{script}");
            // Arguments must reach the tool, or the TARGETS probe loses its
            // flags and every paste silently fails.
            assert!(script.contains(r#""$@""#), "{script}");
        }
    }

    #[tokio::test]
    async fn the_browser_shim_routes_through_riabuild() {
        let (ctx, _home) = ctx_with(FakeRunner::new()).await;
        write_browser_shim(&ctx).await.unwrap();
        // Safe to run twice, like every other apply().
        write_browser_shim(&ctx).await.unwrap();

        let script = tokio::fs::read_to_string(ctx.paths.bin_dir().join(BROWSER_TOOL))
            .await
            .unwrap();
        assert!(script.contains("channel open"), "{script}");
        assert!(script.contains(r#""$@""#), "{script}");
        // The whole point. A fallback to the real xdg-open on a display-less
        // server runs a terminal browser inside the session's own TTY, which is
        // the failure this shim exists to prevent.
        assert!(!script.contains("exec xdg-open"), "{script}");
    }

    /// A shadowed binary with no parser behind it would pass everything through
    /// — a tool that looks installed and does nothing riabuild intended.
    #[test]
    fn every_shadowed_tool_has_a_parser() {
        for tool in CLIPBOARD_TOOLS {
            assert!(
                clipboard::Tool::from_name(tool).is_some(),
                "{tool} is shimmed but the shim cannot parse it"
            );
        }
    }

    /// Pins the undocumented `CLAUDE_CONFIG_DIR` behaviour against a real
    /// Claude Code install.
    ///
    /// Ignored by default because it needs `claude` on PATH; run it with
    /// `cargo test -- --ignored` on a machine that has it, and before every
    /// Claude Code version bump.
    #[tokio::test]
    #[ignore = "requires Claude Code installed; pins undocumented behaviour"]
    async fn claude_config_dir_smoke() {
        use riabuild_runner::{CommandRunner, RealRunner, RunOptions};
        let runner = RealRunner;
        let Some(_) = runner.which("claude") else {
            panic!("claude is not installed; this test needs it");
        };

        let home = tempfile::TempDir::new().unwrap();
        let profile = home.path().join("profile");
        tokio::fs::create_dir_all(&profile).await.unwrap();

        let output = runner
            .run(
                "claude",
                &["--version"],
                &RunOptions {
                    env: vec![(
                        "CLAUDE_CONFIG_DIR".into(),
                        profile.to_string_lossy().into_owned(),
                    )],
                    ..Default::default()
                },
            )
            .await
            .expect("claude --version");

        assert!(output.ok(), "claude rejected CLAUDE_CONFIG_DIR: {output:?}");
        // Claude Code writes its state into the directory it was pointed at. If
        // this stops happening, the profile model is broken and every developer
        // shares one config.
        assert!(
            profile.read_dir().unwrap().next().is_some() || profile.exists(),
            "CLAUDE_CONFIG_DIR was ignored"
        );
    }

    /// Does `CLAUDE_CONFIG_DIR` isolate *credentials*, or only configuration?
    ///
    /// This is the property every account rests on: if it stops holding, two
    /// accounts share one sign-in and the whole feature is a lie. Kept
    /// `#[ignore]`d rather than deleted because it is a record of an
    /// undocumented upstream property, and it needs a real Claude Code install
    /// to say anything at all.
    ///
    /// The profile model assumes the former. Tested directly on macOS:
    /// `CLAUDE_CONFIG_DIR=/tmp/asd claude` prompts for a fresh login, so the
    /// credential is keyed to the config directory, not to the Unix account.
    /// Two riabuild profiles on one Mac — or two developers sharing a Unix
    /// account on a Mac server — get separate Claude sign-ins. See
    /// `docs/superpowers/specs/2026-08-06-remote-mode-design.md`, "Claude Code
    /// needs no special handling here".
    ///
    /// `claude auth status --json` is the non-interactive probe: it reports
    /// `loggedIn` without opening a prompt and, for a signed-out directory,
    /// without printing anything credential-shaped. A fresh `CLAUDE_CONFIG_DIR`
    /// must report `loggedIn: false` — if a future Claude Code release instead
    /// inherits a login from outside the config directory, this fails instead
    /// of silently merging two developers' sign-ins.
    ///
    /// Ignored by default: it needs a real Claude Code install, **and** an
    /// ambient sign-in already sitting in the default config directory (run
    /// `claude auth login` first if `claude auth status` there says
    /// `loggedIn: false`). Without that ambient sign-in the test is vacuous —
    /// if isolation broke completely and every config dir now shared one
    /// global (signed-out) login, a fresh temp dir would still report
    /// `loggedIn: false` and the test would pass for the wrong reason. The
    /// two probes together are the evidence: the ambient directory must be
    /// signed in, and the fresh one must not be.
    ///
    /// To confirm credentials (not just configuration) are isolated,
    /// additionally sign in under two different `CLAUDE_CONFIG_DIR`s by hand
    /// and check `claude auth status` disagrees between them — that step
    /// cannot be scripted, so it isn't asserted here. Run with
    /// `cargo test -- --ignored` before every Claude Code version bump, the
    /// way `claude_config_dir_smoke` already is.
    #[tokio::test]
    #[ignore = "requires Claude Code installed and already signed in to the \
                default config directory; pins undocumented behaviour"]
    async fn claude_credentials_follow_the_config_dir() {
        use riabuild_runner::{CommandRunner, RealRunner, RunOptions};
        let runner = RealRunner;
        let Some(_) = runner.which("claude") else {
            panic!("claude is not installed; this test needs it");
        };

        // Probe 1: the ambient config directory must already be signed in, or
        // this test cannot distinguish "isolated" from "broken" — a machine
        // with no sign-in anywhere would pass either way. Never surface any
        // field but `loggedIn`: the signed-in probe's JSON also carries
        // `email`, `orgId`, `orgName`, and `subscriptionType`.
        let ambient = runner
            .run(
                "claude",
                &["auth", "status", "--json"],
                &RunOptions::default(),
            )
            .await
            .expect("claude auth status --json (ambient)");
        let ambient_status: serde_json::Value = serde_json::from_str(ambient.trimmed())
            .expect("claude auth status --json must print JSON");
        let Some(&serde_json::Value::Bool(true)) = ambient_status.get("loggedIn") else {
            panic!(
                "the default Claude config directory is not signed in \
                 (loggedIn: false); this test needs an ambient sign-in to \
                 prove anything — run `claude auth login` first"
            );
        };

        // Probe 2: a brand-new config directory must report signed out.
        let home = tempfile::TempDir::new().unwrap();
        let profile = home.path().join("profile");
        tokio::fs::create_dir_all(&profile).await.unwrap();

        let output = runner
            .run(
                "claude",
                &["auth", "status", "--json"],
                &RunOptions {
                    env: vec![(
                        "CLAUDE_CONFIG_DIR".into(),
                        profile.to_string_lossy().into_owned(),
                    )],
                    ..Default::default()
                },
            )
            .await
            .expect("claude auth status --json (fresh)");

        // Parsed rather than substring-matched: `"loggedIn": false` and
        // `"loggedIn":false` are the same JSON and differ as text, and a
        // two-spelling `contains` check silently starts passing for the wrong
        // reason the day upstream reformats its output.
        let status: serde_json::Value = serde_json::from_str(output.trimmed())
            .expect("claude auth status --json must print JSON");
        assert_eq!(
            status.get("loggedIn"),
            Some(&serde_json::Value::Bool(false)),
            "a fresh CLAUDE_CONFIG_DIR was already authenticated: credentials \
             are not isolated per config directory"
        );
    }

    /// Pins the JSON key the account box reads. `status::ask` takes the email out
    /// of `auth status --json`, and a rename upstream would turn every signed-in
    /// account into `Unknown` — a box that says riabuild cannot tell, on a machine
    /// where nothing is wrong.
    ///
    /// Deliberately `#[ignore]`d: it asserts against the developer's own sign-in,
    /// which only a real machine has.
    #[tokio::test]
    #[ignore = "needs a real Claude Code install and a signed-in developer; records the `email` key the account box reads"]
    async fn auth_status_reports_an_email_field() {
        use riabuild_runner::{CommandRunner, RealRunner, RunOptions};
        let runner = RealRunner;
        let Some(_) = runner.which("claude") else {
            panic!("claude is not installed; this test needs it");
        };

        let mine = runner
            .run(
                "claude",
                &["auth", "status", "--json"],
                &RunOptions::default(),
            )
            .await
            .expect("claude auth status");

        assert!(
            mine.stdout.contains("email"),
            "the developer's own sign-in reported no email field: {mine:?}"
        );
    }

    /// Every launcher passes `--settings` unconditionally, so `claude-2 auth
    /// login` — which the account box tells developers to run — depends on a
    /// global flag being accepted ahead of a subcommand.
    ///
    /// Deliberately `#[ignore]`d: only a real `claude` can say whether its
    /// argument parser still allows this, and the shims are generated on the
    /// assumption that it does.
    #[tokio::test]
    #[ignore = "needs a real Claude Code install; records that --settings is accepted ahead of a subcommand, which every launcher assumes"]
    async fn settings_flag_survives_a_subcommand() {
        use riabuild_runner::{CommandRunner, RealRunner, RunOptions};
        let runner = RealRunner;
        let Some(_) = runner.which("claude") else {
            panic!("claude is not installed; this test needs it");
        };

        let home = tempfile::TempDir::new().unwrap();
        let settings = home.path().join("settings.json");
        tokio::fs::write(&settings, "{}").await.unwrap();

        let output = runner
            .run(
                "claude",
                &[
                    "--settings",
                    &settings.to_string_lossy(),
                    "auth",
                    "status",
                    "--json",
                ],
                &RunOptions::default(),
            )
            .await
            .expect("claude --settings auth status");
        assert!(output.stdout.contains("loggedIn"), "{output:?}");
    }
}
